### ISSUE TITLE
create conda environment error

### ISSUE THREAD

**Issue by XiongGZ** [jiarong/VirSorter2#115]
When i try to test virsorter2 using command:
`virsorter run -w test.out -i 8seq.fa --min-length 1500 -j 4 all`

I got a error report:
```
[2022-07-22 23:35 INFO] VirSorter 2.2.3
[2022-07-22 23:35 INFO] /home/xiongguangzhou/Software/miniconda3/envs/virsorter2/bin/virsorter run -w test.out -i 8seq.fa --min-length 1500 -j 4 all
[2022-07-22 23:35 INFO] Using /home/xiongguangzhou/Software/VirSorter2/virsorter/template-config.yaml as config template
[2022-07-22 23:35 INFO] conig file written to /home/xiongguangzhou/Software/VirSorter2/test/test.out/config.yaml

[2022-07-22 23:35 INFO] Executing: snakemake --snakefile /home/xiongguangzhou/Software/VirSorter2/virsorter/Snakefile --directory /home/xiongguangzhou/Software/VirSorter2/test/test.out --jobs 4 --configfile /home/xiongguangzhou/Software/VirSorter2/test/test.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /home/xiongguangzhou/Database/VirSorter2/conda_envs --use-conda    --quiet  all   
CreateCondaEnvironmentException:
Could not create conda environment from /home/xiongguangzhou/Software/VirSorter2/virsorter/rules/../envs/vs2.yaml:
Traceback (most recent call last):
  File "/home/xiongguangzhou/Software/miniconda3/envs/virsorter2/bin/mamba", line 7, in <module>
    from mamba.mamba import
  File "/home/xiongguangzhou/Software/miniconda3/envs/virsorter2/lib/python3.8/site-packages/mamba/mamba.py", line 52, in <module>
    import mamba.mamba_api as api
ImportError: /home/xiongguangzhou/Software/miniconda3/envs/virsorter2/lib/python3.8/site-packages/mamba/mamba_api.cpython-38-x86_64-linux-gnu.so: undefined symbol: curl_url_cleanup

  File "/home/xiongguangzhou/Software/miniconda3/envs/virsorter2/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 350, in create
```

Can you @jiarong  help me? 
Thanks !

**Comment by jiarong** [comment]
Did you get error when installing the database? (`virsorter setup`)

**Comment by XiongGZ** [comment]
The database installed  using `virsorter setup` is incomplete, so i download from `https://osf.io/v46sc/download`

**Comment by XiongGZ** [comment]
I solve the problem by reinstalling `mamba`. Thanks !
