### ISSUE TITLE
Error to download the dramv database

### ISSUE THREAD

**Issue by Tsingsjeen** [jiarong/VirSorter2#118]
Hi,

When I am going to download the "db-dramv" following the tutorial, I met an issue below:

# DRAMv: db-dramv
DRAM-setup.py prepare_databases --skip_uniref --output_dir db-dramv

Traceback (most recent call last):
  File "/homemib/Chen/conda/envs/DRAM/bin/DRAM-setup.py", line 5, in <module>
    from mag_annotator.database_processing import prepare_databases, update_dram_forms, \
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_processing.py", line 8, in <module>
    from skbio import read as read_sequence
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/skbio/io/__init__.py", line 247, in <module>
    import_module('skbio.io.format.lsmat')
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/skbio/io/format/lsmat.py", line 77, in <module>
    from skbio.stats.distance import DissimilarityMatrix, DistanceMatrix
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/skbio/stats/distance/__init__.py", line 197, in <module>
    from ._mantel import mantel, pwmantel
  File "/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/skbio/stats/distance/_mantel.py", line 16, in <module>
    from scipy.stats import PearsonRConstantInputWarning
ImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' (/homemib/Chen/conda/envs/DRAM/lib/python3.10/site-packages/scipy/stats/__init__.py)

I also tried to download from "https://github.com/WrightonLabCSU/DRAM", but there also reported the same issue.

Do you know what is the problem?
Great thanks!

Best,

Chen

**Comment by jiarong** [comment]
Hi, it looks like there are some python dependency issues. I would suggest posting this to DRAMv and see what they suggest.
