### ISSUE TITLE
DRAMv - No descriptions were found for your id's.

### ISSUE THREAD

**Issue by carmennns2** [jiarong/VirSorter2#135]
Hi, I am new to Virsorter2 and DRAMv. 

When running DRAMv, I got this error:

DRAM-v.py annotate \
-i /scratch/hdd2/carmen/Metagenomics_16S/Phage/phage_annotation/test2.2/vs2/9968_vs2/for-dramv/final-viral-combined-for-dramv.fa \
-v /scratch/hdd2/carmen/Metagenomics_16S/Phage/phage_annotation/test2.2/vs2/9968_vs2/for-dramv/viral-affi-contigs-for-dramv.tab  \
-o dramv-annotate --threads 30 --min_contig_size 1000  

2022-09-29 12:28:51.428394: Viral annotation started
0:00:00.006462: Retrieved database locations and descriptions
0:00:00.006490: Annotating final-viral-combined-for-dramv
0:00:00.388120: Turning genes from prodigal to mmseqs2 db
0:00:02.223577: Getting hits from kofam
0:04:31.088310: Getting forward best hits from viral
0:04:31.747997: Getting reverse best hits from viral
0:04:32.318992: Getting descriptions of hits from viral
/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/database_handler.py:81: UserWarning: No descriptions were found for your id's. Does this YP_009218533.1 look like an id from viral_description
  warnings.warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
Traceback (most recent call last):
  File "/home/ca3226/miniconda3/envs/DRAM/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_vgfs.py", line 475, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 1013, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 921, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['viral'], tmp_dir,
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 684, in do_blast_style_search
    hits = formater(hits, header_dict)
  File "/home/ca3226/miniconda3/envs/DRAM/lib/python3.10/site-packages/mag_annotator/annotate_bins.py", line 173, in get_basic_description
    header = header_dict[hit]
KeyError: 'YP_009218533.1'

Do you have any suggestions on how to resolve this issue? 

Thank you so much!
Carmen

**Comment by jiarong** [comment]
Looks like an issue with DRAMv database. Try `DRAM-setup.py update_description_db` and see if it fixes the issue. See more details in this thread:
https://github.com/WrightonLabCSU/DRAM/issues/158

**Comment by carmennns2** [comment]
Hi JiaRong, Thank you for the suggestion, `DRAM-setup.py update_description_db`  resolved my issue. (:
