### ISSUE TITLE
when i use virsorter2, i met a question, need some help!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by cbw606** [jiarong/VirSorter2#150]
![c5bae2deaa3c2932c97e19371287feb](https://user-images.githubusercontent.com/127168620/223307739-d6f54841-5c40-4a45-b5dd-346c44cdbb05.png)
just like the picture, please help me.

**Comment by jiarong** [comment]
I have not  seen this before. A few things to check: 1) VS2 is only supported in Linux; Make sure you are using Linux OS. 2) Sometimes update conda version might help.
At last, you can always use installation (option 3)[https://github.com/jiarong/VirSorter2#option-3]

**Comment by cbw606** [comment]
Thanks for your advice, I update the conda, it still doesn't work.  I don;t have enough access to use installation (option 3), so I follow the option 2. It has some error :   
 (vs3) cbw@zwc-Precision-T7610:/media/cbw/chenbowen/FWBViromeAnaysis/MGNJ20200525A14C3A-7N/A20201218-7000_DNA/result/04.Assemble/Env.1round$ virsorter run -w test.out -i Env.1round.asm.final.fa -j 4 all
[2023-03-07 16:22 INFO] VirSorter 2.2.4
[2023-03-07 16:22 INFO] /home/cbw/miniconda3/envs/vs3/bin/virsorter run -w test.out -i Env.1round.asm.final.fa -j 4 all
[2023-03-07 16:22 INFO] Using /media/cbw/chenbowen/miniconda/VirSorter2/virsorter/template-config.yaml as config template
Traceback (most recent call last):
  File "/home/cbw/miniconda3/envs/vs3/bin/virsorter", line 8, in <module>
    sys.exit(cli())
  File "/home/cbw/miniconda3/envs/vs3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cbw/miniconda3/envs/vs3/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cbw/miniconda3/envs/vs3/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cbw/miniconda3/envs/vs3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cbw/miniconda3/envs/vs3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/media/cbw/chenbowen/miniconda/VirSorter2/virsorter/virsorter.py", line 356, in run_workflow
    make_config(
  File "/media/cbw/chenbowen/miniconda/VirSorter2/virsorter/config.py", line 151, in make_config
    groups_avail = os.listdir(f'{db_dir}/group')
FileNotFoundError: [Errno 2] No such file or directory: '/media/cbw/chenbowen/miniconda/VirSorter2/b-dir/group'
 Can you help me?

**Comment by pur80a** [comment]
Looks like you did not install the database (see https://github.com/jiarong/VirSorter2#download-database-and-dependencies). 
Has this issue been resolved? If so, please close it.
