### ISSUE TITLE
Could not create conda environment

### ISSUE THREAD

**Issue by TKsh6** [jiarong/VirSorter2#157]
Cause I chose option3 for installation, but I met this problem,
```
[2023-03-29 21:20 INFO] saving /beegfs/home/syl/database_db/virsorter2 as DBDIR to config file /beegfs/home/syl/.virsorter/template-config.yaml
CreateCondaEnvironmentException:
Could not create conda environment from /usr/local/lib/python3.9/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/lib/python3.9/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 119, in load_channels
        index = get_index(
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 78, in get_index
        for channel in api.get_channels(all_channels):
    RuntimeError: Read-only file system: '/usr/local/pkgs/cache/a549c71d'

`$ /usr/local/bin/mamba create --quiet --file /beegfs/home/syl/database_db/virsorter2/conda_envs/b001bbeb.yaml --prefix /beegfs/home/syl/database_db/virsorter2/conda_envs/b001bbeb`

```
So how can I do to solve this?

yours tk

**Comment by jiarong** [comment]
Hi, you do not need to create env with apptainer version.

**Comment by TKsh6** [comment]
sitll have the problem.

`(base) [syl@node2 test_forvir]$ /beegfs/home/syl/software/virsorter2/virsorter2.sif run -w test.out1 -i test.fa --min-length 1500 -j 4 all -d /beegfs/home/syl/database_db/vir`

```
[2023-03-30 15:54 INFO] VirSorter 2.2.3
[2023-03-30 15:54 INFO] /usr/local/bin/virsorter run -w test.out1 -i test.fa --min-length 1500 -j 4 all -d /beegfs/home/syl/database_db/vir
[2023-03-30 15:54 INFO] Using /beegfs/home/syl/.virsorter/template-config.yaml as config template
[2023-03-30 15:54 INFO] conig file written to /beegfs/home/syl/software/test_forvir/test.out1/config.yaml

[2023-03-30 15:54 INFO] Executing: snakemake --snakefile /usr/local/lib/python3.9/site-packages/virsorter/Snakefile --directory /beegfs/home/syl/software/test_forvir/test.out1 --jobs 4 --configfile /beegfs/home/syl/software/test_forvir/test.out1/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /beegfs/home/syl/database_db/vir/conda_envs --use-conda    --quiet  all
CreateCondaEnvironmentException:
Could not create conda environment from /usr/local/lib/python3.9/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/lib/python3.9/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 119, in load_channels
        index = get_index(
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 78, in get_index
        for channel in api.get_channels(all_channels):
    RuntimeError: Read-only file system: '/usr/local/pkgs/cache/a549c71d'

`$ /usr/local/bin/mamba create --quiet --file /beegfs/home/syl/database_db/vir/conda_envs/30eccc62.yaml --prefix /beegfs/home/syl/database_db/vir/conda_envs/30eccc62`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/beegfs/home/syl/anaconda3/bin/conda
             CONDA_PREFIX=/beegfs/home/syl/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/beegfs/home/syl/anaconda3/bin/python
               CONDA_ROOT=/usr/local
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/beegfs/home/syl/anaconda3/jre/lib/amd64/server
          LD_LIBRARY_PATH=/.singularity.d/libs
                  MANPATH=/beegfs/home/public/opt/lmod/lmod/share/man::/beegfs/root/openmpi-4.1.
                          1/share/man
               MODULEPATH=/beegfs/home/public/opt/easybuild/modules/bio:/beegfs/home/public/opt/
                          PATH/bio/:/beegfs/home/public/opt/easybuild/modules/mpi:/beegfs/home/p
                          ublic/opt/easybuild/modules/all:/beegfs/home/public/opt/modulefiles/Li
                          nux:/beegfs/home/public/opt/modulefiles/Core:/beegfs/home/public/opt/l
                          mod/lmod/modulefiles/Core
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                USER_PATH=/beegfs/home/syl/anaconda3/envs/vs2/lib/python3.10/bin:/beegfs/home/sy
                          l/software/FAPROTAX_1.2.6/collapse_table.py:/beegfs/home/syl/software/
                          bamdst-master/:/beegfs/home/syl/software/site-
                          packages/lefse:/beegfs/home/syl/software/site-
                          packages/lefse-1.1.2.dist-info:/beegfs/home/syl/software/site-
                          packages/lefsebiom:/beegfs/home/syl/software/python-scripts:/beegfs/ho
                          me/syl/software:/beegfs/home/syl/software/quast-5.2.0/bin:/beegfs/home
                          /syl/software/soap/bin:/beegfs/home/syl/software/Trimmomatic-0.39:/bee
                          gfs/home/syl/software/metabat/:/beegfs/home/syl/software/metabat/:/bee
                          gfs/home/syl/software/:/beegfs/home/syl/software/ANIcalculator_v1:/bee
                          gfs/home/syl/software/mummer-4.0.0rc1:/beegfs/home/syl/software/mash-
                          Linux64v2.3:/beegfs/home/syl/software/mash-
                          Linux64v2.3:/beegfs/home/syl/software/RefineM-master/bin:/beegfs/home/
                          syl/database_db/gtdb:/beegfs/home/syl/software/Checkm_data:/beegfs/hom
                          e/syl/.aspera/connect/bin:/beegfs/home/syl/anaconda3/bin:/beegfs/home/
                          syl/anaconda3/bin:/beegfs/home/syl/anaconda3/condabin:/usr/local/bin:/
                          usr/bin:/usr/local/sbin:/usr/sbin:/beegfs/root/openmpi-4.1.1/bin:/beeg
                          fs/root/software/stubl-master/bin:/beegfs/root/software/pestat:/beegfs
                          /root/software/GTX.Zip:/opt/ibutils/bin:/usr/local/cuda-11.4/bin:/beeg
                          fs/home/syl/.local/bin:/beegfs/home/syl/bin:/bin:/usr/bin:/sbin:/usr/s
                          bin:/usr/local/bin:/usr/local/sbin

     active environment : /beegfs/home/syl/anaconda3
    active env location : /beegfs/home/syl/anaconda3
            shell level : 1
       user config file : /beegfs/home/syl/.condarc
 populated config files : /beegfs/home/syl/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local  (read only)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /beegfs/home/syl/.conda/pkgs
       envs directories : /beegfs/home/syl/.conda/envs
                          /usr/local/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Linux/3.10.0-1062.18.1.el7.x86_64 debian/10 glibc/2.28
                UID:GID : 1036:1001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 350, in create

```

**Comment by jiarong** [comment]
Try below:
```
/beegfs/home/syl/software/virsorter2/virsorter2.sif run -w test.out1 -i test.fa --min-length 1500 -j 4 all
```

**Comment by TKsh6** [comment]
It says it doesn't have the db file here.
```
(base) [syl@node2 test_forvir]$ /beegfs/home/syl/software/virsorter2/virsorter2.sif run -w test.out1 -i test.fa --min-length 1500 -j 4 all
[2023-03-30 16:00 INFO] VirSorter 2.2.3
[2023-03-30 16:00 INFO] /usr/local/bin/virsorter run -w test.out1 -i test.fa --min-length 1500 -j 4 all
[2023-03-30 16:00 INFO] Using /beegfs/home/syl/.virsorter/template-config.yaml as config template
Traceback (most recent call last):
  File "/usr/local/bin/virsorter", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/virsorter/virsorter.py", line 356, in run_workflow
    make_config(
  File "/usr/local/lib/python3.9/site-packages/virsorter/config.py", line 151, in make_config
    groups_avail = os.listdir(f'{db_dir}/group')
FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/home/syl/database_db/virsorter2/group'

```

**Comment by jiarong** [comment]
Aha, you need to delete this file:
```
rm /beegfs/home/syl/.virsorter/template-config.yaml
```

**Comment by jiarong** [comment]
Just a note for others having the same issue:
With the apptainer version, you do not need to worry about the database. However, if you have run the `virsorter setup` or `virsorter run --db-dir`, you need to delete the `.virsorter/template-config.yaml` file in your user home directory.

**Comment by TKsh6** [comment]
Thank you for your help, it worked.

**Comment by pur80a** [comment]
I think this issue is ready to be closed.
