### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dnolin13** [jiarong/VirSorter2#160]
Hello,
Not sure what is going on with this error, but here is the error:
[2023-05-01 16:03 ERROR] See error details in /home/nolin/SPOTV_quals_subset/13_Viral_Contigs/VirSorter2-nolin/log/iter-0/step3-classify/provirus-score-merge.log
[Mon May  1 16:03:43 2023]
Error in rule merge_provirus_call_from_groups:
    jobid: 21
    output: iter-0/viral.partseq.tsv.tmp, iter-0/viral.fullseq.tsv.tmp
    conda-env: /home/nolin/software/db/conda_envs/9abeeeb5
    shell:
        
            Log=/home/nolin/SPOTV_quals_subset/13_Viral_Contigs/VirSorter2-nolin/log/iter-0/step3-classify/provirus-score-merge.log
            python /home/nolin/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/merge-provirus-from-groups.py iter-0/dsDNAphage/all.pdg.prv.bdy,iter-0/ssDNA/all.pdg.prv.bdy dsDNAphage,ssDNA iter-0/viral.partseq.tsv.tmp iter-0/viral.fullseq.tsv.tmp 2> $Log || { echo "See error details in $Log" | python /home/nolin/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

And here is the log: 

(base) nolin@ada:~/SPOTV_quals_subset$ more /home/nolin/SPOTV_quals_subset/13_Viral_Contigs/VirSorter2-nolin/log/iter-0/step3-classify/provirus-score-merge.log
Traceback (most recent call last):
  File "/home/nolin/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/merge-provirus-from-groups.py", line 123, in <module>
    main()
  File "/home/nolin/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/merge-provirus-from-groups.py", line 38, in main
    seqnames = [name.rsplit('||', 1)[0] for name in df['seqname']]
  File "/home/nolin/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/merge-provirus-from-groups.py", line 38, in <listcomp>
    seqnames = [name.rsplit('||', 1)[0] for name in df['seqname']]
AttributeError: 'float' object has no attribute 'rsplit'

**Comment by jiarong** [comment]
Hi, this error is likely to be caused by sequence name being all numeric. You can prefix them with some alphabetic label to get around this.
