### ISSUE TITLE
Error: ValueError: invalid version number 'UserWarning:'

### ISSUE THREAD

**Issue by HaimAshk** [jiarong/VirSorter2#163]
Hi,

Thanks for maintaining this tool. I have installed the latest Virsorter2 development version (from github) into a new conda env, following the instructions in 'option 2'

When trying to run it with the example sequence provided I get the following error:

virsorter run -w test.out -i test.fa --min-length 1500 -j 4 all
```
[2023-05-11 15:51 INFO] VirSorter 2.2.4
[2023-05-11 15:51 INFO] /tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/bin/virsorter run -w test.out -i test.fa --min-length 1500 -j 4 all
[2023-05-11 15:51 INFO] Using /tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/VirSorter2/virsorter/template-config.yaml as config template
[2023-05-11 15:51 INFO] conig file written to /ebio/test.out/config.yaml

[2023-05-11 15:51 INFO] Executing: snakemake --snakefile /tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/VirSorter2/virsorter/Snakefile --directory /ebio/abt6//test.out --jobs 4 --configfile /ebio/abt6//test.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/DB/db/conda_envs --use-conda    --quiet  all   
Traceback (most recent call last):
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/__init__.py", line 662, in snakemake
    success = workflow.execute(
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/workflow.py", line 856, in execute
    dag.create_conda_envs(
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/dag.py", line 280, in create_conda_envs
    env.create(dryrun)
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 247, in create
    conda = Conda(self._container_img)
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 381, in __new__
    inst.__init__(container_img=container_img)
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 394, in __init__
    self._check()
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 448, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/setuptools/_distutils/version.py", line 54, in __init__
    self.parse(vstring)
  File "/tmp/global2//Programs/miniconda3/envs/VirSorter2.2.4/lib/python3.8/site-packages/setuptools/_distutils/version.py", line 157, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'UserWarning:'
```

This is ow my conda env looks like:
conda list
```
# packages in environment at /tmp/global2/Programs/miniconda3/envs/VirSorter2.2.4:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aioeasywebdav             2.4.0           py38h578d9bd_1001    conda-forge
aiohttp                   3.8.4            py38h1de0b5d_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
atk-1.0                   2.38.0               hd4edc92_1    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2            py38h0a891b7_1    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boto3                     1.26.132           pyhd8ed1ab_0    conda-forge
botocore                  1.29.132           pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py38h0a891b7_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h35add3b_1015    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py38h4a40e3a_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
coin-or-cbc               2.10.10              h9002f0b_0    conda-forge
coin-or-cgl               0.60.7               h516709c_0    conda-forge
coin-or-clp               1.17.8               h1ee7a9c_0    conda-forge
coin-or-osi               0.108.8              ha2443b9_0    conda-forge
coin-or-utils             2.11.9               hee58242_0    conda-forge
coincbc                   2.10.10           0_metapackage    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1           py38h578d9bd_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py38hfbd4bf9_0    conda-forge
cryptography              40.0.2           py38h3d167d9_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
datrie                    0.8.2            py38h0a891b7_6    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
docutils                  0.20             py38h578d9bd_0    conda-forge
dropbox                   11.36.1          py38h06a4308_0  
expat                     2.5.0                hcb278e6_1    conda-forge
fftw                      3.3.10          nompi_hc118613_107    conda-forge
filechunkio               1.8                        py_2    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.4           py38h01eb140_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.3.3            py38h0a891b7_0    conda-forge
ftputil                   5.0.4              pyhd8ed1ab_0    conda-forge
gdk-pixbuf                2.42.10              h6b639ba_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
ghostscript               9.54.0               h27087fc_2    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.31             pyhd8ed1ab_0    conda-forge
google-api-core           2.11.0             pyhd8ed1ab_0    conda-forge
google-api-python-client  2.86.0             pyhd8ed1ab_0    conda-forge
google-auth               2.18.0             pyh1a96a4e_0    conda-forge
google-auth-httplib2      0.1.0              pyhd8ed1ab_1    conda-forge
google-cloud-core         2.3.2              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.9.0              pyh1a96a4e_0    conda-forge
google-crc32c             1.5.0            py38h5eee18b_0  
google-resumable-media    2.5.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.57.1             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.14               h295c915_1  
graphviz                  8.0.5                h28d9a01_0    conda-forge
grpcio                    1.54.2           py38h8dc9893_0    conda-forge
gtk2                      2.24.33              h90689f9_2    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hmmer                     3.3                  he1b5a44_1    bioconda
httplib2                  0.22.0             pyhd8ed1ab_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagemagick               7.1.1_8         pl5321hfda792c_0    conda-forge
imbalanced-learn          0.7.0                      py_0    conda-forge
importlib-metadata        6.6.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py38h578d9bd_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py38h43d8883_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.0      cxx17_hcb278e6_1    conda-forge
libarchive                3.6.2                h3d51595_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.0.1                h588be90_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgd                     2.3.3                hfa28ad5_6    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.76.2               hebfc3b9_0    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgrpc                   1.54.2               hcf146ea_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2            py38h7fa060d_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
librsvg                   2.56.0               h5cef280_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libsqlite                 3.41.2               h2797004_1    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                ha587672_6    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.3.0                hb47c5f0_0    conda-forge
libwebp-base              1.3.0                h0b41bf4_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.4               hfdac1af_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2            py38haad2881_0    conda-forge
markupsafe                2.1.2            py38h1de0b5d_0    conda-forge
matplotlib-base           3.7.1            py38hd6c3c57_0    conda-forge
multidict                 6.0.4            py38h1de0b5d_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.24.3           py38h59b608b_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.1            py38h01efb38_1    conda-forge
pango                     1.50.14              heaa33ce_1    conda-forge
paramiko                  3.1.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.5.0            py38h961100d_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkg-config                0.29.2            h36c2ea0_1008    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.5.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prettytable               3.7.0              pyhd8ed1ab_0    conda-forge
prodigal                  2.6.3                hec16e2b_4    bioconda
protobuf                  4.21.12          py38h8dc9893_0    conda-forge
psutil                    5.9.5            py38h1de0b5d_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pulp                      2.7.0            py38h578d9bd_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                      py_0  
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py38h0a891b7_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pygraphviz                1.10             py38h96794d7_4    conda-forge
pynacl                    1.5.0            py38h0a891b7_2    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3           py38h1de0b5d_0    conda-forge
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.16          he550d4f_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-irodsclient        1.1.6              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      3_cp38    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h0a891b7_5    conda-forge
ratelimiter               1.2.0           pyhd8ed1ab_1003    conda-forge
re2                       2023.02.02           hcb278e6_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.26          py38h01eb140_0    conda-forge
ruamel.yaml.clib          0.2.7            py38h1de0b5d_1    conda-forge
s3transfer                0.6.1              pyhd8ed1ab_0    conda-forge
scikit-learn              0.22.1           py38hcdab131_1    conda-forge
scipy                     1.10.1           py38h59f1b5f_2    conda-forge
screed                    1.1.2              pyhd8ed1ab_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slacker                   0.14.0                     py_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakemake                 5.26.0                        0    bioconda
snakemake-minimal         5.26.0                     py_0    bioconda
statsmodels               0.14.0           py38h31356c5_1    conda-forge
stone                     3.3.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
unicodedata2              15.0.0           py38h0a891b7_0    conda-forge
uritemplate               4.1.1              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
virsorter                 2.2.4                    pypi_0    pypi
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0           py38h1de0b5d_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
yarl                      1.9.1            py38h01eb140_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0           py38h5945529_1    conda-forge
zstd                      1.5.5                hc292b87_0  
```

Same happened when installing using the instructions under 'option 1'. 
Any advice how to solve it?

Thanks in advance for any suggestion!

**Comment by Guillaume-Marseille** [comment]
Having the same issue.
I post this to follow the thread.

**Comment by andriangajigan** [comment]
I have similar issues as well.

**Comment by ChaoLab** [comment]
I have a similar issue too. Wondering who has solved this issue?

**Comment by jiarong** [comment]
Hi all,
It looks like an update on python is breaking the code. It takes sometime to get the conda installation updated. Meanwhile, you use the two solutions:
1) use option 3 (the apptainer image). @Guillaume-Marseille, the image has database and dependencies included within it, so it's the most stable and reliable. You can run it directly w/o database setup, eg.  `/path/to/virsorter2.sif run -w test.out -i test.fa --min-length 1500 -j 4 all`

2) Run the this command line before running VS2 from conda version:  `export PYTHONWARNINGS="ignore::Warning"`

**Comment by ChaoLab** [comment]
Hi,
I used the following commands:
```
mamba create -c bioconda -c conda-forge -p /path/to/conda_envs/ViWrap-vs2 python=3.8 virsorter=2.2.4 numpy=1.20.0 -y

export PYTHONWARNINGS="ignore::Warning"

virsorter setup -d VirSorter2_db -j 4
```

But I still failed to use virsorter2 and download the database:

![image](https://github.com/jiarong/VirSorter2/assets/35715202/205ce3fc-ea8d-4286-94c5-7c7907489c6d)

**Comment by jiarong** [comment]
@ChaoLab , how did you activate the `ViWrap-vs2` env (something like `conda activate ViWrap-vs2`) before the `export` command?
The following works in my test:
```
mamba create -c conda-forge -c bioconda -n vs2 python=3.8 virsorter=2.2.4 -y
conda activate vs2
export PYTHONWARNINGS="ignore::Warning"
virsorter setup -d VirSorter2_db -j 4
```

**Comment by ChaoLab** [comment]
@jiarong Yes, I was in the conda env 
![image](https://github.com/jiarong/VirSorter2/assets/35715202/aca72588-276b-4c11-bb9c-2393f5dec506)

**Comment by jiarong** [comment]
@ChaoLab , how did you activate the ViWrap-vs2 env? I am wondering the way getting in the env might make a difference..

**Comment by ChaoLab** [comment]
It is “conda activate /storage2/scratch/zzhou388/ViWrap/conda_envs/ViWrap-vs2”

**Comment by jiarong** [comment]
@ChaoLab , no clue why it works in my server but not yours.. For conda version, you can also try the following:
```
mamba create -n vs2 -c conda-forge -c bioconda virsorter=2 conda-package-handling=1.9
```

**Comment by shaze** [comment]
I am getting a similar problem using `apptainer`


```
apptainer exec virsorter2.sif virsorter setup -d db -j 4
[2025-05-21 11:16 INFO] VirSorter 2.2.3
[2025-05-21 11:16 INFO] /usr/local/bin/virsorter setup -d db -j 4
[2025-05-21 11:16 INFO] Setting up VirSorter2 database; this might take ~10 mins and only needs to be done once.
[2025-05-21 11:16 INFO] Attention: can not write template-config.yaml in source directory:
/usr/local/lib/python3.9/site-packages/virsorter
makeing a copy to user home direcotry:
/home/scott/.virsorter/template-config.yaml

[2025-05-21 11:16 INFO] Using {template} as config template
[2025-05-21 11:16 INFO] saving /home/scott/db as DBDIR to config file /home/scott/.virsorter/template-config.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/snakemake/__init__.py", line 662, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.9/site-packages/snakemake/workflow.py", line 856, in execute
    dag.create_conda_envs(
  File "/usr/local/lib/python3.9/site-packages/snakemake/dag.py", line 280, in create_conda_envs
    env.create(dryrun)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 247, in create
    conda = Conda(self._container_img)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 381, in __new__
    inst.__init__(container_img=container_img)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 394, in __init__
    self._check()
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 448, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/usr/local/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'warning:'
[2025-05-21 11:16 INFO] First attempt failed; trying the second time.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/snakemake/__init__.py", line 662, in snakemake
    success = workflow.execute(
  File "/usr/local/lib/python3.9/site-packages/snakemake/workflow.py", line 856, in execute
    dag.create_conda_envs(
  File "/usr/local/lib/python3.9/site-packages/snakemake/dag.py", line 280, in create_conda_envs
    env.create(dryrun)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 247, in create
    conda = Conda(self._container_img)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 381, in __new__
    inst.__init__(container_img=container_img)
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 394, in __init__
    self._check()
  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 448, in _check
    if StrictVersion(version) < StrictVersion("4.2"):
  File "/usr/local/lib/python3.9/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.9/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number 'warning:'
```
