### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by MalloryCunninghamVCU** [jiarong/VirSorter2#164]
I have successfully run VirSorter2 on the test dataset.  I wanted to try the same test script on some sample data.  I continually get the following error message, even though I have tried splitting the large fasta file into smaller chunks as recommended in earlier issue responses.  

(vs2) root@MallorysHP:~/VirSorter2_Test# virsorter run -w test.out2 -i 1009595Ck141_12733.fa --min-length 1500 -j 4 all
[2023-05-11 12:42 INFO] VirSorter 2.2.4
[2023-05-11 12:42 INFO] /root/miniconda3/envs/vs2/bin/virsorter run -w test.out2 -i 1009595Ck141_12733.fa --min-length 1500 -j 4 all
[2023-05-11 12:42 INFO] Using /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/template-config.yaml as config template
[2023-05-11 12:42 INFO] conig file written to /root/VirSorter2_Test/test.out2/config.yaml

[2023-05-11 12:42 INFO] Executing: snakemake --snakefile /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/Snakefile --directory /root/VirSorter2_Test/test.out2 --jobs 4 --configfile /root/VirSorter2_Test/test.out2/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /root/miniconda3/envs/db/conda_envs --use-conda    --quiet  all
Job counts:
        count   jobs
        1       all
        1       check_point_for_reclassify
        1       circular_linear_split
        1       classify
        2       classify_by_group
        2       classify_full_and_part_by_group
        1       combine_linear_circular
        2       combine_linear_circular_by_group
        1       extract_feature
        1       extract_provirus_seqs
        1       finalize
        1       gff_feature
        2       gff_feature_by_group
        2       hmm_features_by_group
        1       hmm_sort_to_best_hit_taxon
        2       hmm_sort_to_best_hit_taxon_by_group
        1       merge_classification
        1       merge_full_and_part_classification
        2       merge_hmm_gff_features_by_group
        2       merge_provirus_call_by_group_by_split
        1       merge_provirus_call_from_groups
        5       merge_split_hmmtbl
        10      merge_split_hmmtbl_by_group
        10      merge_split_hmmtbl_by_group_tmp
        1       pick_viral_fullseq
        1       preprocess
        1       split_faa
        2       split_faa_by_group
        2       split_gff_by_group
        61
Traceback (most recent call last):
  File "/root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 98, in <module>
    main()
  File "/root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 59, in main
    for rec in screed.open(infile):
  File "/root/miniconda3/envs/db/conda_envs/02fa5a66/lib/python3.8/site-packages/screed/openscreed.py", line 35, in __init__
    self.iter_fn = self.open_reader(filename, *args, **kwargs)
  File "/root/miniconda3/envs/db/conda_envs/02fa5a66/lib/python3.8/site-packages/screed/openscreed.py", line 92, in open_reader
    raise ValueError("unknown file format for '%s'" % filename)
ValueError: unknown file format for '/root/VirSorter2_Test/1009595Ck141_12733.fa'
[Thu May 11 12:42:05 2023]
Error in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    conda-env: /root/miniconda3/envs/db/conda_envs/02fa5a66
    shell:

        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /root/VirSorter2_Test/1009595Ck141_12733.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi

        python /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py           /root/VirSorter2_Test/1009595Ck141_12733.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           1500

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"
 | python /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /root/miniconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by jiarong** [comment]
Hi, it likes like there is some format issue within `/root/VirSorter2_Test/1009595Ck141_12733.fa`. Make sure it's fasta format.
