### ISSUE TITLE
[BUG] in writeMPS with open(filename, "w") as f: FileNotFoundError: [Errno 2] No such file or directory: 'tmp/d43ef73e150d46648f4e326813c760da-pulp.mps'

### ISSUE THREAD

**Issue by erfanshekarriz** [jiarong/VirSorter2#176]
Hello! 

I wanted to report a strange bug I'm seeing. When running 

```
virsorter run -i output/2__assembly/contigs/CRC_meta.fa -w test/  --db-dir pipeline/database/vs2/         -j 1  --prep-for-dramv --min-length 200 --min-score 0 --include-groups dsDNAphage,ssDNA         all
```

I ran into the following error:
```
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/snakemake/__init__.py", line 662, in snakemake
    success = workflow.execute(
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/snakemake/workflow.py", line 977, in execute
    success = scheduler.schedule()
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/snakemake/scheduler.py", line 425, in schedule
    run = self.job_selector(needrun)
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/snakemake/scheduler.py", line 660, in job_selector_ilp
    prob.solve()
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/pulp.py", line 1913, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/apis/coin_api.py", line 137, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/apis/coin_api.py", line 153, in solve_CBC
    vs, variablesNames, constraintsNames, objectiveName = lp.writeMPS(
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/pulp.py", line 1782, in writeMPS
    return mpslp.writeMPS(self, filename, mpsSense=mpsSense, rename=rename, mip=mip)
  File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/mps_lp.py", line 250, in writeMPS
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/d43ef73e150d46648f4e326813c760da-pulp.mps'
```

I get an identical error when I replace ```test/``` with any other directory, but surprisingly it works when I set it to the current ```.``` directory.  It keeps on telling me ```File "/home/username/miniconda3/envs/vs2/lib/python3.10/site-packages/pulp/mps_lp.py", line 250, in writeMPS
    with open(filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/d43ef73e150d46648f4e326813c760da-pulp.mps'```

The strange part is that it only happens on one of the servers I use that operates with CentOS7. Two other servers that have CentOS7 and CentOS8 work perfectly fine. 

I have no idea where the issue is coming from but my guess is how VS2 handles $TMPDIR since on the server I'm having issues with I have no access to the $TMPDIR and instead assign my own using export TMPDIR=tmp. 

Wanted to report and see if the issue can be resolved, running into reproducibility issues across platforms. 

If you need any documents to investigate feel free to let me know!!

Best, 

Erfan

**Comment by erfanshekarriz** [comment]
UPDATES:

I've come closer to the solution here. If I restart the server and do NOT set ```export TMPDIR=tmp``` then setting the output directory ```-w``` works. 

Is there a way around this where we can set our own $TMPDIR or where virsorter temporary assigns this and reassigns to its original value after running?

Best, 

Erfan

**Comment by jiarong** [comment]
Hi, generally all users should have access to `/tmp` (ie., $TMPDIR). If you want to change, you can use `virsorter config --set LOCAL_SCRATCH=PATH_TO_DIR`.
