### ISSUE TITLE
TypeError: reduction operation 'argmax' not allowed for this dtype

### ISSUE THREAD

**Issue by VrusaWvary** [jiarong/VirSorter2#18]
Hello,  
when I run command `virsorter run -w virsorter2/final-viral-boundary.tsv -i contigs.fa --include-groups "dsDNAphage,ssDNA" -j 8 --min-score 0.8 --db-dir references/virsorter2_db --use-conda-off` , I get an error reading TypeError: reduction operation 'argmax' not allowed for this dtype, I ran some samples, most of them were running normally, only a few samples reported an error. This is the full error message I receive:

>Traceback (most recent call last):
 File "/data2/envs/src/virsorter2-master/virsorter/./scripts/get-seq-w-lt2gene-w-hallmark.py", line 64, in <module>
 main()
 File "/data2/envs/src/virsorter2-master/virsorter/./scripts/get-seq-w-lt2gene-w-hallmark.py", line 32, in main
 group_ser = df.idxmax(axis=1)
 File "/data2/envs/713b2092/lib/python3.8/site-packages/pandas/core/frame.py", line 8079, in idxmax
 indices = nanops.nanargmax(self.values, axis=axis, skipna=skipna)
 File "/data2/envs/713b2092/lib/python3.8/site-packages/pandas/core/nanops.py", line 64, in _f
 raise TypeError(
TypeError: reduction operation 'argmax' not allowed for this dtype

Thanks!

**Comment by jiarong** [comment]
Is `virsorter2/final-viral-boundary.tsv` your intended output directory?
You can try:
```
virsorter run -w virsorter2-new-try  -i contigs.fa --include-groups "dsDNAphage,ssDNA" -j 8 --min-score 0.8 --db-dir references/virsorter2_db --use-conda-off
```
and see if the same error shows up.

**Comment by algaraber** [comment]
Hi:

I get a similar error to the one VrusaWvary mentions. It happens once step 2 (extraction of features) is completed.
Is it ok if I post the error file here or should I open a new issue?

Thanks

**Comment by VrusaWvary** [comment]
Hi, @jiarong 
I tried `virsorter run -w virsorter2-new-try  -i contigs.fa --include-groups "dsDNAphage,ssDNA" -j 8 --min-score 0.8 --db-dir references/virsorter2_db --use-conda-off`, but I'm still getting same error.
Thanks!

**Comment by jiarong** [comment]
@VrusaWvary, can you check what's in `virsorter2-new-try/iter-0/all-hallmark-cnt.tsv`?

**Comment by VrusaWvary** [comment]
@jiarong sorry, I didn't find it, this is all the files in the `virsorter2-new-try/iter-0/`:
>all.fna
all-fullseq-proba.tsv
all.pdg.Archaea.hmmtbl
all.pdg.Bacteria.hmmtbl
all.pdg.Eukaryota.hmmtbl
all.pdg.faa
all.pdg.faa.splitdir
all.pdg.faa.ss
all.pdg.gff
all.pdg.gff.ftr
all.pdg.hmm.ftr
all.pdg.hmm.tax
all.pdg.Mixed.hmmtbl
all.pdg.Viruses.hmmtbl
dsDNAphage
pp-linear.faa
pp-linear-flt.faa
pp-linear-flt.gff
pp-linear.fna
pp-linear.fna.splitdir
pp-linear.gff
pp-seqname-length.tsv
ssDNA
viral-fullseq.tsv
viral-lt2gene-w-hallmark.fa.tmp
viral-partseq.tsv

 I added the log, maybe it's helpful.
>[2020-11-26 09:36 INFO] # of seqs < 0 bp and removed: 0
[2020-11-26 09:36 INFO] # of circular seqs: 0
[2020-11-26 09:36 INFO] # of linear seqs  : 1
[2020-11-26 09:36 INFO] No circular seqs found in contig file
[2020-11-26 09:36 INFO] Finish spliting linear contig file with common rbs
[2020-11-26 09:36 INFO] Step 1 - preprocess finished.
[2020-11-26 09:42 INFO] Step 2 - extract-feature finished.
[2020-11-26 09:42 ERROR] See error details in /data2/virs/virsorter-new-try/log/iter-0/step3-classify/pick-viral-f
ullseq.log
[Wed Nov 26 09:42:50 2020]
Error in rule pick_viral_fullseq:
    jobid: 22
    output: iter-0/viral-fullseq.fa, iter-0/all-hallmark-cnt.tsv, iter-0/viral-lt2gene-w-hallmark.fa

**Comment by jiarong** [comment]
I see you have only have 1 sequence. Is it OK to  zip the `virsorter2-new-try` directory and post it here?

**Comment by jiarong** [comment]
I have updated the development version yesterday. It might have solved the issue. Can you update and try again. I just tested 1 viral sequence or 1 nonviral sequence and both finished successfully.

**Comment by VrusaWvary** [comment]
I didn't get the same error, but I got the new one, This is the full error message I receive:
>[2020-12-02 16:47 INFO] # of seqs < 0 bp and removed: 0
[2020-12-02 16:47 INFO] # of circular seqs: 0
[2020-12-02 16:47 INFO] # of linear seqs  : 1
[2020-12-02 16:47 INFO] No circular seqs found in contig file
[2020-12-02 16:47 INFO] Finish spliting linear contig file with common rbs
[2020-12-02 16:47 INFO] Step 1 - preprocess finished.
[2020-12-02 16:53 INFO] Step 2 - extract-feature finished.
[2020-12-02 16:53 ERROR] See error details in /data2/virs/virsorter2-new-try/log/iter-0/step3-classify/provirus-score-dsDNAphage.log
[2020-12-02 16:53 ERROR] See error details in /data2/virs/virsorter2-new-try/log/iter-0/step3-classify/provirus-score-ssDNA.log
[Wed Dec  2 16:53:56 2020]
[Wed Dec  2 16:53:56 2020]
Error in rule classify_full_and_part_by_group:
Error in rule classify_full_and_part_by_group:
    jobid: 23
    jobid: 24
    output: iter-0/dsDNAphage/viral.trim.clf
    output: iter-0/ssDNA/viral.trim.clf


provirus-score-dsDNAphage.log
>Traceback (most recent call last):
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 269, in <module>
    main()
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 265, in main
    clf_trim_ins.load_data()
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 71, in load_data
    seqnames, indice = zip(
ValueError: not enough values to unpack (expected 2, got 0)

provirus-score-ssDNA.log
>Traceback (most recent call last):
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 269, in <module>
    main()
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/share/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data2/envs/713b2092/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 265, in main
    clf_trim_ins.load_data()
  File "/data2/envs/src/virsorter2-master/virsorter/./scripts/classify-trimed.py", line 71, in load_data
    seqnames, indice = zip(
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by jiarong** [comment]
@VrusaWvary Do you mind sharing the one sequence you used?

**Comment by VrusaWvary** [comment]
@jiarong Yes, I have sent it to your mailbox.

**Comment by jiarong** [comment]
@VrusaWvary Thanks for provide the sequence. The bug is fixed. You can update following development version installation instruction.

**Comment by VrusaWvary** [comment]
Thanks! It works now.
