### ISSUE TITLE
Error:non-zero exit code

### ISSUE THREAD

**Issue by jojyjohn28** [jiarong/VirSorter2#181]
Please help,

I am getting the following error. I am working on centralized HPC system without root permission. I tried --use-conda-off, it did'nt worke

[Fri Nov 10 11:57:04 2023]
localcheckpoint circular_linear_split:
    input: /zfs/camplab/0_data_recleaned/MT_trimmed_140/tr140_cleaned/140_CP_Spr01G08_RNA1.fq
    output: iter-0/pp-seqname-length.tsv
    jobid: 7
Downstream jobs will be updated after completion.

Activating conda environment: /zfs/camplab/Jojy/darpa_working/virsorter/db/conda_envs/354bc54a
[Fri Nov 10 11:57:09 2023]
Error in rule circular_linear_split:
    jobid: 7
    output: iter-0/pp-seqname-length.tsv
    conda-env: /zfs/camplab/Jojy/darpa_working/virsorter/db/conda_envs/354bc54a
    shell:
        
        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /zfs/camplab/0_data_recleaned/MT_trimmed_140/tr140_cleaned/140_CP_Spr01G08_RNA1.fq)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /zfs/gcl/software/gbf/anaconda3/2021.11/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi 

        python /zfs/gcl/software/gbf/anaconda3/2021.11/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py           /zfs/camplab/0_data_recleaned/MT_trimmed_140/tr140_cleaned/140_CP_Spr01G08_RNA1.fq           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           0

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /zfs/gcl/software/gbf/anaconda3/2021.11/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /zfs/gcl/software/gbf/anaconda3/2021.11/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /zfs/gcl/software/gbf/anaconda3/2021.11/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by jiarong** [comment]
Hi,  Is `/zfs/camplab/0_data_recleaned/MT_trimmed_140/tr140_cleaned/140_CP_Spr01G08_RNA1.fq` short reads? If so, VirSorter2 does not work with  short reads, only assembled contigs. If not, can you paste the whole log output from VirSorter2 here?

**Comment by jojyjohn28** [comment]
I solved this issue using the assembled file.
However I am facing module not found error for Screed. I am working on HPC system of my University, and when I contacted them they are telling it is not possible to install/update the tool. please see the answer from them below. (Unfortunately, due to the developmental version requiring mamba, we are unable to install it as a CUGBF module.)
So I am looking for an option to install it on Conda env.
_conda create -n vs2 -c bioconda -c conda-forge python=3 scikit-learn=0.22.1 imbalanced-learn pandas seaborn hmmer prodigal screed ruamel.yaml snakemake=5.16.0 click_
Will this work? or do you have any other suggestions.

**Comment by jiarong** [comment]
Hi, sorry for the late reply. If HPC has installed VirSorter2 for you, then you should not need to install again. The "Screed error" is probably caused by other reason (most likely you have changed your PATH setting in .bashrc). Anyway, you can use installation option 3 that using aptainer/singularity HPC should have installed too.

**Comment by hdflorezr** [comment]
Hello. Please help with an issue.

I'm running Metaphage and I'm having some issues with virsorter2. I had an Error:non-zero exit code. I'm using long reads and this is the message from the log file:

Traceback (most recent call last):
  File "/home/omicas/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/home/omicas/miniconda3/envs/metaphage2/lib/python3.7/site-packages/virsorter/./scripts/classify.py", line 60, in main
    model = joblib.load(model_f)
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/pickle.py", line 1579, in find_class
    __import__(module, level=0)
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/ensemble/__init__.py", line 7, in <module>
    from ._forest import RandomForestClassifier
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 56, in <module>
    from ..tree import (DecisionTreeClassifier, DecisionTreeRegressor,
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/tree/__init__.py", line 6, in <module>
    from ._classes import BaseDecisionTree
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 40, in <module>
    from ._criterion import Criterion
  File "sklearn/tree/_splitter.pxd", line 34, in init sklearn.tree._criterion
  File "sklearn/tree/_tree.pxd", line 37, in init sklearn.tree._splitter
  File "sklearn/neighbors/_quad_tree.pxd", line 55, in init sklearn.tree._tree
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/neighbors/__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/neighbors/_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/decomposition/__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/decomposition/dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/linear_model/__init__.py", line 12, in <module>
    from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV,
  File "/media/omicas/data/Datos_Hernan/MetaPhage/db/virsorter/virsorter2/conda_envs/def5e359/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 30, in <module>
    method='lar', copy_X=True, eps=np.finfo(np.float).eps,
  File "/home/omicas/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

I appreciate your help. Thank you in advance.

**Comment by jiarong** [comment]
Hi, you can uninstall the numpy install in `/home/omicas/.local` or simply rename the path to something else.

**Comment by hdflorezr** [comment]
I tried to uninstalling numpy and that action showed me an error. I installed again numpy and I'm working under the version 1.20.0 and I'm having the same issue. What other solution could I take?

Thanks.

**Comment by jiarong** [comment]
hi, you can simply rename the path `/home/omicas/.local` to something else.
