### ISSUE TITLE
virsorter2 error

### ISSUE THREAD

**Issue by Microbion** [jiarong/VirSorter2#187]
My command is `nextflow run replikation/What_the_Phage 
		 -r v1.2.1 
		 -offline true 
		 -profile local,singularity 
		 --databases /home/jovyan/.conda/envs/databases 
		 --cores 5 
		 --fasta /home/jovyan/work/水稻240/contig_clu/contig_rep.fa 
		 --filter 3000 
		 --output wtp_visorter2 
		 --identify 
		  -with-tower`.

It reports a virsorter2 error: 
<details><summary>Details</summary>
<p>

[2023-12-21 17:07 INFO] VirSorter 2.2
[2023-12-21 17:07 INFO] /opt/conda/bin/virsorter run -d db -w virsorter2_da3470b9ce3a3973c4c42902f6ac93.out -i contig_rep_filtered.fa -j 5 --provirus-off
[2023-12-21 17:07 INFO] "template-config.yaml" has not been initialized; initializing..
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/virsorter/config.py", line 96, in make_config
    with open(TEMPLATE) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.8/site-packages/virsorter/template-config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/virsorter", line 10, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
 File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/virsorter/virsorter.py", line 354, in run_workflow
    make_config(
  File "/opt/conda/lib/python3.8/site-packages/virsorter/config.py", line 120, in make_config
    config = init_config_template(SRC_CONFIG_DIR, 
  File "/opt/conda/lib/python3.8/site-packages/virsorter/config.py", line 46, in init_config_template
    os.makedirs(user_config_dir, exist_ok=True)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/home/jovyan/.virsorter'
`.
I have tried virsorter2 by singularity with command: ```
singularity run singularity_images/papanikos-virsorter-2-2.2.1--fa935f8.img virsorter run -d /home/jovyan/work/.config/.conda/envs/databases/virsorter2-db/db/  -w virsort_debug -i /tmp/nextflow-phages-jovyan/67/8cf656851ca3eb6f70aa3b7097146c/contig_rep_filtered.fa -j 5 --provirus-off

</p>
</details> 

I have tried virsorter2 by singularity with command: `
singularity run singularity_images/papanikos-virsorter-2-2.2.1--fa935f8.img virsorter run -d /home/jovyan/work/.config/.conda/envs/databases/virsorter2-db/db/  -w virsort_debug -i /tmp/nextflow-phages-jovyan/67/8cf656851ca3eb6f70aa3b7097146c/contig_rep_filtered.fa -j 5 --provirus-off`.And it performed well with logs: 
<details><summary>Details</summary>
<p>

2023-12-21 17:01 INFO] VirSorter 2.2
[2023-12-21 17:01 INFO] /opt/conda/bin/virsorter run -d /home/jovyan/work/.config/.conda/envs/databases/virsorter2-db/db/ -w virsort_debug -i /tmp/nextflow-phages-jovyan/67/8cf656851ca3eb6f70aa3b7097146c/contig_rep_filtered.fa -j 5 --provirus-off
[2023-12-21 17:01 INFO] "template-config.yaml" has not been initialized; initializing..
[2023-12-21 17:01 INFO] Attention: can not write template-config.yaml in source directory:
/opt/conda/lib/python3.8/site-packages/virsorter
makeing a copy to user home direcotry:
/home/jovyan/.virsorter/template-config.yaml

[2023-12-21 17:01 INFO] Using {template} as config template
[2023-12-21 17:01 INFO] saving /home/jovyan/work/.config/.conda/envs/databases/virsorter2-db/db as DBDIR to config file /home/jovyan/.virsorter/template-config.yaml
[2023-12-21 17:01 INFO] conig file written to /home/jovyan/work/水稻240/bio_test/virsort_debug/config.yaml

</p>
</details> 

My nextflow version is 23.10.0 and singularity version is 3.8.6. Why nexflow pipeline went wrong?

**Comment by Microbion** [comment]
Sorry for confusing git respository. This issue should be closed.

**Comment by jiarong** [comment]
Right, it should be posted to what_the_phage project.
