### ISSUE TITLE
run issues

### ISSUE THREAD

**Issue by Xugh1** [jiarong/VirSorter2#202]
Hi, when I run virsorter2,  I got this issue:
CreateCondaEnvironmentException:
Could not create conda environment from /conda_envs/vs2/lib/python3.10/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/conda_envs/vs2/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/conda_envs/vs2/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
      File "/conda_envs/vs2/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/conda_envs/vs2/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 162, in execute
        result[installer_type] = installer.install(
      File "/conda_envs/vs2/lib/python3.10/site-packages/mamba/mamba_env.py", line 54, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/conda_envs/vs2/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
        index = get_index(
      File "/conda_envs/vs2/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (7) Couldn't connect to server [http://localhost/anaconda/cloud/conda-forge/noarch/repodata.json]
    Failed to connect to localhost port 80 after 0 ms: Couldn't connect to server
How can I solve it?

**Comment by jiarong** [comment]
Hi, this error message is showing `mamba` can not connect to conda server. Please check your internet connection is working.

**Comment by Xugh1** [comment]
OK. Thank you for your reply.
