### ISSUE TITLE
error of step3

### ISSUE THREAD

**Issue by 2061574124** [jiarong/VirSorter2#204]
**run code just following: virsorter run -w out -i /home/dell/database/H1_assembly.contigs.fa --min-length 1000 -j 16 all**
[2024-06-20 00:55 INFO] VirSorter 2.2.3
[2024-06-20 00:55 INFO] /home/dell/miniconda3/envs/vs2/bin/virsorter run -w out -i /home/dell/database/H1_assembly.contigs.fa --min-length 1000 -j 16 all
[2024-06-20 00:55 INFO] Using /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/template-config.yaml as config template
[2024-06-20 00:55 INFO] conig file written to /home/dell/database/out/config.yaml

[2024-06-20 00:55 INFO] Executing: snakemake --snakefile /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/Snakefile --directory /home/dell/database/out --jobs 16 --configfile /home/dell/database/out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /home/dell/database/virsorter/conda_envs --use-conda    --quiet  all   
Job counts:
	count	jobs
	1	all
	1	check_point_for_reclassify
	1	circular_linear_split
	1	classify
	2	classify_by_group
	2	classify_full_and_part_by_group
	1	combine_linear_circular
	2	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	2	gff_feature_by_group
	2	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	2	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	2	merge_hmm_gff_features_by_group
	2	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	10	merge_split_hmmtbl_by_group
	10	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	2	split_faa_by_group
	2	split_gff_by_group
	61
[2024-06-20 00:55 INFO] # of seqs < 1000 bp and removed: 93518
[2024-06-20 00:55 INFO] # of circular seqs: 60
[2024-06-20 00:55 INFO] # of linear seqs  : 30941
[2024-06-20 00:55 INFO] Finish spliting circular contig file with common rbs
[2024-06-20 00:55 INFO] Finish spliting linear contig file with common rbs
[2024-06-20 00:58 INFO] Step 1 - preprocess finished.
                                                                                                            
[2024-06-20 03:41 INFO] Step 2 - extract-feature finished.
[2024-06-20 03:41 ERROR] S**ee error details in /home/dell/database/out/log/iter-0/step3-classify/all-score-dsDNAphage.log
[2024-06-20 03:41 ERROR] See error details in /home/dell/database/out/log/iter-0/step3-classify/all-score-ssDNA.log
[Thu Jun 20 03:41:20 2024]
[Thu Jun 20 03:41:20 2024]
Error in rule classify_by_group:
Error in rule classify_by_group:
    jobid: 56
    jobid: 57
    output: iter-0/dsDNAphage/all.pdg.clf
    output: iter-0/ssDNA/all.pdg.clf
    conda-env: /home/dell/database/virsorter/conda_envs/3bfc9270
    conda-env: /home/dell/database/virsorter/conda_envs/3bfc9270
    shell:
        
        Log=/home/dell/database/out/log/iter-0/step3-classify/all-score-dsDNAphage.log
        python /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py iter-0/dsDNAphage/all.pdg.ftr /home/dell/database/virsorter/group/dsDNAphage/model dsDNAphage iter-0/dsDNAphage/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        Log=/home/dell/database/out/log/iter-0/step3-classify/all-score-ssDNA.log
        python /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py iter-0/ssDNA/all.pdg.ftr /home/dell/database/virsorter/group/ssDNA/model ssDNA iter-0/ssDNA/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message**

*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

after setup, when performed "virsorter2 run" was exit, i wonder how to fix.
THANKS!

**Comment by 2061574124** [comment]
and this is the **error details in /home/dell/database/out/log/iter-0/step3-classify/all-score-dsDNAphage.log:**

Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 60, in main
    model = joblib.load(model_f)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1579, in find_class
    __import__(module, level=0)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/__init__.py", line 7, in <module>
    from ._forest import RandomForestClassifier
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 56, in <module>
    from ..tree import (DecisionTreeClassifier, DecisionTreeRegressor,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/__init__.py", line 6, in <module>
    from ._classes import BaseDecisionTree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 40, in <module>
    from ._criterion import Criterion
  File "sklearn/tree/_splitter.pxd", line 34, in init sklearn.tree._criterion
  File "sklearn/tree/_tree.pxd", line 37, in init sklearn.tree._splitter
  File "sklearn/neighbors/_quad_tree.pxd", line 55, in init sklearn.tree._tree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/__init__.py", line 12, in <module>
    from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 30, in <module>
    method='lar', copy_X=True, eps=np.finfo(np.float).eps,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by 2061574124** [comment]
and this is the **error details in /home/dell/database/out/log/iter-0/step3-classify/all-score-dsDNAphage.log:**

Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 60, in main
    model = joblib.load(model_f)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1579, in find_class
    __import__(module, level=0)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/__init__.py", line 7, in <module>
    from ._forest import RandomForestClassifier
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 56, in <module>
    from ..tree import (DecisionTreeClassifier, DecisionTreeRegressor,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/__init__.py", line 6, in <module>
    from ._classes import BaseDecisionTree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 40, in <module>
    from ._criterion import Criterion
  File "sklearn/tree/_splitter.pxd", line 34, in init sklearn.tree._criterion
  File "sklearn/tree/_tree.pxd", line 37, in init sklearn.tree._splitter
  File "sklearn/neighbors/_quad_tree.pxd", line 55, in init sklearn.tree._tree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/__init__.py", line 12, in <module>
    from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 30, in <module>
    method='lar', copy_X=True, eps=np.finfo(np.float).eps,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by 2061574124** [comment]
and this is the error details in /home/dell/database/out/log/iter-0/step3-classify/**all-score-ssDNAphage.log**:

Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 60, in main
    model = joblib.load(model_f)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1537, in load_stack_global
    self.append(self.find_class(module, name))
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1579, in find_class
    __import__(module, level=0)
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/__init__.py", line 7, in <module>
    from ._forest import RandomForestClassifier
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 56, in <module>
    from ..tree import (DecisionTreeClassifier, DecisionTreeRegressor,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/__init__.py", line 6, in <module>
    from ._classes import BaseDecisionTree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 40, in <module>
    from ._criterion import Criterion
  File "sklearn/tree/_splitter.pxd", line 34, in init sklearn.tree._criterion
  File "sklearn/tree/_tree.pxd", line 37, in init sklearn.tree._splitter
  File "sklearn/neighbors/_quad_tree.pxd", line 55, in init sklearn.tree._tree
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/__init__.py", line 17, in <module>
    from ._nca import NeighborhoodComponentsAnalysis
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/_nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/__init__.py", line 17, in <module>
    from .dict_learning import dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/dict_learning.py", line 4, in <module>
    from . import _dict_learning
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py", line 21, in <module>
    from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/__init__.py", line 12, in <module>
    from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 30, in <module>
    method='lar', copy_X=True, eps=np.finfo(np.float).eps,
  File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by 2061574124** [comment]
> and this is the error details in /home/dell/database/out/log/iter-0/step3-classify/**all-score-ssDNAphage.log**:
> 
> Traceback (most recent call last): File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in main() File "/home/dell/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 60, in main model = joblib.load(model_f) File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 658, in load obj = _unpickle(fobj, filename, mmap_mode) File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle obj = unpickler.load() File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1212, in load dispatch[key[0]](self) File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1537, in load_stack_global self.append(self.find_class(module, name)) File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/pickle.py", line 1579, in find_class **import**(module, level=0) File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/**init**.py", line 7, in from ._forest import RandomForestClassifier File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 56, in from ..tree import (DecisionTreeClassifier, DecisionTreeRegressor, File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/**init**.py", line 6, in from ._classes import BaseDecisionTree File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 40, in from ._criterion import Criterion File "sklearn/tree/_splitter.pxd", line 34, in init sklearn.tree._criterion File "sklearn/tree/_tree.pxd", line 37, in init sklearn.tree._splitter File "sklearn/neighbors/_quad_tree.pxd", line 55, in init sklearn.tree._tree File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/**init**.py", line 17, in from ._nca import NeighborhoodComponentsAnalysis File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/neighbors/_nca.py", line 22, in from ..decomposition import PCA File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/**init**.py", line 17, in from .dict_learning import dict_learning File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/dict_learning.py", line 4, in from . import _dict_learning File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/decomposition/_dict_learning.py", line 21, in from ..linear_model import Lasso, orthogonal_mp_gram, LassoLars, Lars File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/**init**.py", line 12, in from ._least_angle import (Lars, LassoLars, lars_path, lars_path_gram, LarsCV, File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/sklearn/linear_model/_least_angle.py", line 30, in method='lar', copy_X=True, eps=np.finfo(np.float).eps, File "/home/dell/database/virsorter/conda_envs/3bfc9270/lib/python3.8/site-packages/numpy/**init**.py", line 305, in **getattr** raise AttributeError(**former_attrs**[attr]) AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Does this mean that numpy version that Virsorer2 conda environment is incorrect?**

**Comment by jiarong** [comment]
This is different from issue #90 where you also commented.  The most recent version 2.2.4 should have addressed the `numpy.float` deprecation issue. Or you can use the container version in installation (option 3)[ https://github.com/jiarong/VirSorter2?tab=readme-ov-file#option-3].

**Comment by mengyuan-JI** [comment]
Hi, I meet the same error , have you solved it?

**Comment by sandraaran** [comment]
Hi, have you solved this error ??
