### ISSUE TITLE
Error message in "circular-linear-split"

### ISSUE THREAD

**Issue by adijatj** [jiarong/VirSorter2#212]
Hi, I am trying to run virsorter2 on my contig sequences. I keep encountering this error in "circular-linear-split". At first, I thought i had duplicate sequence names but I checked and there were none. Could you please help? I'm using python 3.10 version for virsorter2. Thanks.

`[2024-07-27 23:17 INFO] VirSorter 2.2.4
[2024-07-27 23:17 INFO] /home/jmhadi001/.conda/envs/virsorter2/bin/virsorter run --keep-original-seq -i /scratch/jmhadi001/IPL_pooledshotgun/megahit_assembled/HJ1/HJ1_contigs_gt1000bp_virso.fa -w HJ1_vs2_phages --include-groups dsDNAphage,ssDNA --min-length 5000 --min-score 0.5 -j 28 all
[2024-07-27 23:17 INFO] Using /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/template-config.yaml as config template
[2024-07-27 23:17 INFO] conig file written to /scratch/jmhadi001/IPL_pooledshotgun/phage_id/virsorter_run_Jul24/HJ1_vs2_phages/config.yaml

[2024-07-27 23:17 INFO] Executing: snakemake --snakefile /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/Snakefile --directory /scratch/jmhadi001/IPL_pooledshotgun/phage_id/virsorter_run_Jul24/HJ1_vs2_phages --jobs 28 --configfile /scratch/jmhadi001/IPL_pooledshotgun/phage_id/virsorter_run_Jul24/HJ1_vs2_phages/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /scratch/jmhadi001/IPL_pooledshotgun/databases/db-vs2/conda_envs --use-conda    --quiet  all
Job counts:
        count   jobs
        1       all
        1       check_point_for_reclassify
        1       circular_linear_split
        1       classify
        2       classify_by_group
        2       classify_full_and_part_by_group
        1       combine_linear_circular
        2       combine_linear_circular_by_group
        1       extract_feature
        1       extract_provirus_seqs
        1       finalize
        1       gff_feature
        2       gff_feature_by_group
        2       hmm_features_by_group
        1       hmm_sort_to_best_hit_taxon
        2       hmm_sort_to_best_hit_taxon_by_group
        1       merge_classification
        1       merge_full_and_part_classification
        2       merge_hmm_gff_features_by_group
        2       merge_provirus_call_by_group_by_split
        1       merge_provirus_call_from_groups
        5       merge_split_hmmtbl
        10      merge_split_hmmtbl_by_group
        10      merge_split_hmmtbl_by_group_tmp
        1       pick_viral_fullseq
        1       preprocess
        1       split_faa
        2       split_faa_by_group
        2       split_gff_by_group
        61
  File "/home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 63
    mes = (f'Duplicate seqname detected in {infile}; '
                                                     ^
SyntaxError: invalid syntax
[Sat Jul 27 23:18:18 2024]
Error in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    conda-env: /scratch/jmhadi001/IPL_pooledshotgun/databases/db-vs2/conda_envs/c9823a7f
    shell:

        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /scratch/jmhadi001/IPL_pooledshotgun/megahit_assembled/HJ1/HJ1_contigs_gt1000bp_virso.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi

        python /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py           /scratch/jmhadi001/IPL_pooledshotgun/megahit_assembled/HJ1/HJ1_contigs_gt1000bp_virso.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           5000

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /home/jmhadi001/.conda/envs/virsorter2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message`

**Comment by jiarong** [comment]
Hi, the error indicates issues with installation. I recommend installation option 3.

**Comment by katemortensen** [comment]
Hi there, 

I'm experiencing a similar error message however I'm using singularity (installation option 3). I suspect it may have to do with circular-linear-split.py regarding the "screed" module. Any guidance would be much appreciated. 

commands:

module load apptainer
which singularity 
cd /home/kmorten/CheckD/bin
singularity run -B /home/kmorten/hifi/NM2022/humanO1/MAGs:/mnt/host_files /home/kmorten/CheckD/bin/virsorter2.sif run -w test_out -i /mnt/host_files/bin.0.fa --min-length 1500 -j 1 all --use-conda-off


error:

[2024-08-30 19:47 INFO] VirSorter 2.2.3
[2024-08-30 19:47 INFO] /usr/local/bin/virsorter run -w test_out -i /mnt/host_files/bin.0.fa --min-length 1500 -j 1 all --use-conda-off
[2024-08-30 19:47 INFO] Using /usr/local/lib/python3.9/site-packages/virsorter/template-config.yaml as config template
[2024-08-30 19:47 INFO] conig file written to /home/kmorten/CheckD/bin/test_out/config.yaml

[2024-08-30 19:47 INFO] Executing: snakemake --snakefile /usr/local/lib/python3.9/site-packages/virsorter/Snakefile --directory /home/kmorten/CheckD/bin/test_out --jobs 1 --configfile /home/kmorten/CheckD/bin/test_out/config.yaml --latency-wait 600 --rerun-incomplete --nolock        --quiet  all   
Job counts:
	count	jobs
	1	all
	1	check_point_for_reclassify
	1	circular_linear_split
	1	classify
	2	classify_by_group
	2	classify_full_and_part_by_group
	1	combine_linear_circular
	2	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	2	gff_feature_by_group
	2	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	2	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	2	merge_hmm_gff_features_by_group
	2	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	10	merge_split_hmmtbl_by_group
	10	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	2	split_faa_by_group
	2	split_gff_by_group
	61
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/virsorter/./scripts/circular-linear-split.py", line 6, in <module>
    import screed
ModuleNotFoundError: No module named 'screed'
[Fri Aug 30 19:47:38 2024]
Error in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    shell:
        
        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /mnt/host_files/bin.0.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /usr/local/lib/python3.9/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi 

        python /usr/local/lib/python3.9/site-packages/virsorter/./scripts/circular-linear-split.py           /mnt/host_files/bin.0.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           1500

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /usr/local/lib/python3.9/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /usr/local/lib/python3.9/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /usr/local/lib/python3.9/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

**Comment by jiarong** [comment]
@katemortensen , your error is different, but the solution is the same. There is some python modules not set up correctly in your container. You can use the container suggested in [installation option 3](https://github.com/jiarong/VirSorter2?tab=readme-ov-file#option-3).

**Comment by katemortensen** [comment]
I was finally able to get virsorter to run from a python script! I used apptainer and singularity (installation method 3). I had tried this method before but didn't realize the read/write/execute restrictions with singularity and the .sif file. The problem was that I didn't build and run the .sif file in the same directory as where I instructed virsorter to write the output. 

@jiarong Thank you for your help and patience!

**Comment by meisiy** [comment]
> Hi, the error indicates issues with installation. I recommend installation option 3.


Hi, I'm using my uni's HPC which using conda/mamba would be easier. Does it have to use the install option 3 to address this problem? 

I have the similar problem when trying the test data:

```
Traceback (most recent call last):
  File "/home2/xxxxxxxx/miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 6, in <module>
    import screed
ModuleNotFoundError: No module named 'screed'
[Tue Feb 11 16:58:21 2025]
Error in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    conda-env: /scratch/xxxxxxxx//Schier/program-dbs/vs2-db/conda_envs/4f6093f0
    shell:

        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /scratch/xxxxxxxx//Schier/VM_wkdir/verifiy_viral_contigs-vs2/test.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /home2/xxxxxxxx//miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi

        python /home2/xxxxxxxx/miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py           /scratch/xxxxxxx/Schier/VM_wkdir/verifiy_viral_contigs-vs2/test.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           1500

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /home2/xxxxxxx/miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /home2/xxxxxxx/miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /home2/xxxxxxx/miniforge3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
```
