### ISSUE TITLE
can VirSorter2 run without an internet connection after installation?

### ISSUE THREAD

**Issue by JIAJ-lab** [jiarong/VirSorter2#224]
Hello, can VirSorter2 run without an internet connection after installation? I'm using the virsorter2.sif in a container on a cluster without internet access and I'm still getting errors that suggest I need to create a Conda environment. I've tried many methods, but it seems I can't use it on the cluster without internet. Do you have any good solutions? Thank you.

/share/home/pjsbjzyjktz/e17301351/container/singularity/virsorter2.sif run -w vs2-outERR10818366 -i ERR10818366_new.contigs.fa -j 50 all
[2024-11-11 19:20 INFO] VirSorter 2.2.3
[2024-11-11 19:20 INFO] /usr/local/bin/virsorter run -w vs2-outERR10818366 -i ERR10818366_new.contigs.fa -j 50 all
[2024-11-11 19:20 INFO] Using /share/home/pjsbjzyjktz/e17301351/.virsorter/template-config.yaml as config template
[2024-11-11 19:20 INFO] conig file written to /share/home/pjsbjzyjktz/e17301351/microbiome/PRJEB59350/rawdata/fastp/vs2-outERR10818366/config.yaml

[2024-11-11 19:20 INFO] Executing: snakemake --snakefile /usr/local/lib/python3.9/site-packages/virsorter/Snakefile --directory /share/home/pjsbjzyjktz/e17301351/microbiome/PRJEB59350/rawdata/fastp/vs2-outERR10818366 --jobs 50 --configfile /share/home/pjsbjzyjktz/e17301351/microbiome/PRJEB59350/rawdata/fastp/vs2-outERR10818366/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /share/home/pjsbjzyjktz/e17301351/database/db/conda_envs --use-conda    --quiet  all   
CreateCondaEnvironmentException:
Could not create conda environment from /usr/local/lib/python3.9/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/lib/python3.9/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 119, in load_channels
        index = get_index(
      File "/usr/local/lib/python3.9/site-packages/mamba/utils.py", line 100, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
    Resolving timed out after 9101 milliseconds

`$ /usr/local/bin/mamba create --quiet --file /share/home/pjsbjzyjktz/e17301351/database/db/conda_envs/47c7d62c.yaml --prefix /share/home/pjsbjzyjktz/e17301351/database/db/conda_envs/47c7d62c`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/.singularity.d/libs
                  MANPATH=:/opt/skyformai/share/man
               MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/
                          usr/share/modulefiles
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                USER_PATH=/share/home/pjsbjzyjktz/e17301351/.local/bin:/share/home/pjsbjzyjktz/e
                          17301351/bin:/usr/lpp/mmfs/bin:/usr/share/Modules/bin:/usr/local/bin:/
                          usr/bin:/usr/local/sbin:/usr/sbin:/opt/skyformai/bin:/bin:/bin:/usr/bi
                          n:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

     active environment : None
       user config file : /share/home/pjsbjzyjktz/e17301351/.condarc
 populated config files : /share/home/pjsbjzyjktz/e17301351/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local  (read only)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /share/home/pjsbjzyjktz/e17301351/.conda/pkgs
       envs directories : /share/home/pisbizyiktz/e17301351/database/db/conda_envs
                          /share/home/pjsbjzyjktz/e17301351/.conda/envs
                          /usr/local/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Linux/4.18.0-513.5.1.el8_9.x86_64 debian/10 glibc/2.28
                UID:GID : 2793:2793
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

  File "/usr/local/lib/python3.9/site-packages/snakemake/deployment/conda.py", line 350, in create

**Comment by jiarong** [comment]
Hi, the container version should be self contained with everything needed. It looks like you have installed the conda version before, which left a config directory in your HOME directory and confuse the container version where the database is. You can just delete that directory: `/share/home/pjsbjzyjktz/e17301351/.virsorter`.

**Comment by asd1864714** [comment]
The same error, is it solved now?

**Comment by JIAJ-lab** [comment]
> The same error, is it solved now?

yes,you can use the virsorter2.sif in a container on a cluster without internet

**Comment by Mars-fi** [comment]
> > The same error, is it solved now?
> 
> yes,you can use the virsorter2.sif in a container on a cluster without internet

How to use virsorter2.sif ?

**Comment by JIAJ-lab** [comment]
> > > The same error, is it solved now?同样的错误，现在解决了吗？
> > 
> > 
> > yes,you can use the virsorter2.sif in a container on a cluster without internet是的，您可以在没有互联网的集群上的容器中使用 virsorter2.sif
> 
> How to use virsorter2.sif ?如何使用 virsorter2.sif ？

Yes, the issue has been resolved. At the time, my cluster had no internet access, so I used it via a Singularity container with the command:  
`apptainer build virsorter2.sif docker://jiarong/virsorter:latest`  
However, before this, I had installed it multiple times using conda, which left some residual paths that weren't fully cleaned up. By following the solution provided by the author—deleting the directory `/share/home/pjsbjzyjktz/e17301351/.virsorter`—I succeeded.  

The command I executed was:  
`singularity exec /share/home/pjsbjzyjktz/e17301351/container/singularity/virsorter2.sif virsorter run -w vs2-outERR10818366 -i ERR10818366_new.contigs.fa -j 50 all`  

I hope this helps. Currently, my cluster has internet access, so I haven't been using this method recently. Thanks for the invitation to answer.

**Comment by LsssssSJ** [comment]
> Hi, the container version should be self contained with everything needed. It looks like you have installed the conda version before, which left a config directory in your HOME directory and confuse the container version where the database is. You can just delete that directory: `/share/home/pjsbjzyjktz/e17301351/.virsorter`.

Great, it works!
