### ISSUE TITLE
issue during virsorter2 run

### ISSUE THREAD

**Issue by TLyan-ze** [jiarong/VirSorter2#27]
Hi! I faced the following error when I used test.fa . Could you please help me?
[2020-12-16 11:29 INFO] Using /hwfssz5/ST_INFECTION/GlobalDatabase/share/software/Miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/template-config.yaml as config template
[2020-12-16 11:29 INFO] conig file written to /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/test/test4.out/config.yaml

[2020-12-16 11:29 INFO] Executing: snakemake --snakefile /hwfssz5/ST_INFECTION/GlobalDatabase/share/software/Miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/Snakefile --directory /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/test/test4.out --jobs 4 --configfile /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/test/test4.out/config.yaml --conda-prefix /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/database/db/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all
Job counts:
        count   jobs
        1       all
        1       check_point_for_reclassify
        1       circular_linear_split
        1       classify
        5       classify_by_group
        5       classify_full_and_part_by_group
        1       combine_linear_circular
        5       combine_linear_circular_by_group
        1       extract_feature
        1       extract_provirus_seqs
        1       finalize
        1       gff_feature
        5       gff_feature_by_group
        5       hmm_features_by_group
        1       hmm_sort_to_best_hit_taxon
        5       hmm_sort_to_best_hit_taxon_by_group
        1       merge_classification
        1       merge_full_and_part_classification
        5       merge_hmm_gff_features_by_group
        5       merge_provirus_call_by_group_by_split
        1       merge_provirus_call_from_groups
        5       merge_split_hmmtbl
        25      merge_split_hmmtbl_by_group
        25      merge_split_hmmtbl_by_group_tmp
        1       pick_viral_fullseq
        1       preprocess
        1       split_faa
        5       split_faa_by_group
        5       split_gff_by_group
        121
[2020-12-16 11:32 INFO] # of seqs < 0 bp and removed: 0
[2020-12-16 11:32 INFO] # of circular seqs: 1
[2020-12-16 11:32 INFO] # of linear seqs  : 8
[2020-12-16 11:32 INFO] Finish spliting linear contig file with common rbs
[2020-12-16 11:32 INFO] Finish spliting linear contig file with NCLDV rbs
[2020-12-16 11:32 INFO] Finish spliting circular contig file with common rbs
[2020-12-16 11:32 INFO] Finish spliting circular contig file with NCLDV rbs
[2020-12-16 11:32 INFO] Step 1 - preprocess finished.
[2020-12-16 11:36 ERROR] See error details in /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/test/test4.out/log/iter-0/step2-extract-feature/extract-feature-from-gff-common.log
[Wed Dec 16 11:36:33 2020]
Error in rule gff_feature:
    jobid: 24
    output: iter-0/all.pdg.gff.ftr
    log: log/iter-0/step2-extract-feature/extract-feature-from-gff-common.log (check log file(s) for error message)
    conda-env: /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/database/db/conda_envs/ed5c4b8c
    shell:

        python /hwfssz5/ST_INFECTION/GlobalDatabase/share/software/Miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/extract-feature-from-gff.py /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/database/db/rbs/rbs-catetory.tsv iter-0/all.pdg.gff iter-0/all.pdg.gff.ftr &> log/iter-0/step2-extract-feature/extract-feature-from-gff-common.log || { echo "See error details in /ldfssz1/ST_INFECTION/P20Z10200N0206_pathogendb/yanzeqin/test/test4.out/log/iter-0/step2-extract-feature/extract-feature-from-gff-common.log" | python /hwfssz5/ST_INFECTION/GlobalDatabase/share/software/Miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at : https://github.com/jiarong/VirSorter2/issues

**This is the message in circular-remove-partial-gene-common.log file!!!!!**
Traceback (most recent call last):
  File "/hwfssz5/ST_INFECTION/GlobalDatabase/share/software/Miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/extract-feature-from-gff.py", line 10, in <module>
    import pandas as pd
  File "/home/yanzeqin/.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
ModuleNotFoundError: No module named 'pandas.compat'

**The command I entered is，**
virsorter run -w test4.out -i  test.fa -j 4 all
 Thank you!

**Comment by jiarong** [comment]
Looks like there is some issue with the installed packages. You can try and rerun the installation step (remove the existing one first).
