### ISSUE TITLE
issue during virsorter2 run

### ISSUE THREAD

**Issue by MeggyC** [jiarong/VirSorter2#29]
Hi there, I've recieved the follwing issue when running virsorter2
[2020-12-18 05:43 INFO] # of seqs < 1000 bp and removed: 0
[2020-12-18 05:43 INFO] # of circular seqs: 1294
[2020-12-18 05:43 INFO] # of linear seqs  : 62424
[2020-12-18 05:43 INFO] Finish spliting circular contig file with common rbs
[2020-12-18 05:43 INFO] Finish spliting linear contig file with common rbs
[2020-12-18 05:45 INFO] Step 1 - preprocess finished.
[2020-12-18 10:58 INFO] Step 2 - extract-feature finished.
[2020-12-18 11:06 ERROR] See error details in /srv/projects/coral/Accelerate_project/analyses/20201002_viral_prep/20201218_VIRSorter2_RNA_viruses/iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.log
[Fri Dec 18 11:06:44 2020]
Error in rule provirus_call_by_group_by_split:
    jobid: 86
    output: iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.bdy, iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.ftr
    conda-env: /srv/home/s4549287/db/conda_envs/cadc5396
    shell:

            Log=/srv/projects/coral/Accelerate_project/analyses/20201002_viral_prep/20201218_VIRSorter2_RNA_viruses/iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.log
            Hallmark_list_f=/srv/home/s4549287/db/group/RNA/hallmark-gene.list
            if [ -s $Hallmark_list_f ]; then
                python /srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/provirus.py iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split iter-0/RNA/all.pdg.hmm.tax /srv/home/s4549287/db/rbs/rbs-catetory.tsv /srv/home/s4549287/db/group/RNA/model iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.bdy iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.ftr --fullseq-clf iter-0/all-fullseq-proba.tsv --group RNA --proba 0.5 --hallmark /srv/home/s4549287/db/group/RNA/hallmark-gene.list 2> $Log || { echo "See error details in $Log" | python /srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
            else
                python /srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/prophage.py iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split iter-0/RNA/all.pdg.hmm.tax /srv/home/s4549287/db/rbs/rbs-catetory.tsv /srv/home/s4549287/db/group/RNA/model iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.bdy iter-0/RNA/all.pdg.gff.splitdir/all.pdg.gff.0.split.prv.ftr --fullseq-clf iter-0/all-fullseq-proba.tsv --group RNA --proba 0.5 2> $Log || { echo "See error details in $Log" | python /srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
            fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

Looking at the log file suggested: 

Traceback (most recent call last):
  File "/srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/provirus.py", line 638, in <module>
    main()
  File "/srv/home/s4549287/db/conda_envs/cadc5396/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/srv/home/s4549287/db/conda_envs/cadc5396/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/srv/home/s4549287/db/conda_envs/cadc5396/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/home/s4549287/db/conda_envs/cadc5396/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/provirus.py", line 635, in main
    provirus_ins.find_boundary()
  File "/srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/provirus.py", line 572, in find_boundary
    self.process_one_contig(last_seqname, last_seqlen, mat)
  File "/srv/home/s4549287/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/provirus.py", line 312, in process_one_contig
    if pr_full < PROVIRUS_CHECK_MAX_FULLSEQ_PROBA and \
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The initial command was:

virsorter run -w /srv/projects/coral/Accelerate_project/analyses/20201002_viral_prep/20201218_VIRSorter2_RNA_viruses/ -i /srv/projects/coral/Accelerate_project/analyses/20201002_viral_prep/RNA_sequences/len1000contigs.fasta --include-groups "RNA" --min-length 1000 --prep-for-dramv

Do you have any pointers? 
Thanks,
Megan

**Comment by jiarong** [comment]
I can not tell from the output. Do you mind send me the result folder `20201218_VIRSorter2_RNA_viruses`? Is this the only sample you ran and failed?
