### ISSUE TITLE
screed missing from 'standard' conda install ? 

### ISSUE THREAD

**Issue by eawebb** [jiarong/VirSorter2#3]
hi i got an error with my samples, but the test dataset worked fine.  This is appears to be easy to fix. when i installed i used the standard noarch conda recipe, and it did not install screed ...not sure why? also, it appears that screed was not required for the test dataset, because it ran fine.  it looks like the conda command you just sent fixed this.

Error log file below:

[2020-07-24 21:44 INFO] Executing: snakemake --snakefile /scratch/eawebb/miniconda/envs/virsorter2/lib/python3.8/site-packages/virsorter/Snakefile --directory /scratch/eawebb/output_webb_1.out --jobs 16 --configfile /scratch/eawebb/output_webb_1.out/config.yaml --conda-prefix /scratch/eawebb/db/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all
Job counts:
	count	jobs
	1	all
	1	circular_linear_split
	1	classify
	3	classify_by_group
	1	combine_linear_circular
	3	combine_linear_circular_by_group
	1	extract_feature
	1	finalize
	1	gff_feature
	3	gff_feature_by_group
	3	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	3	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	3	merge_hmm_gff_features_by_group
	5	merge_split_hmmtbl
	15	merge_split_hmmtbl_by_group
	15	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	3	split_faa_by_group
	68
[2020-07-24 21:45 INFO] # of seqs < 0 bp and removed: 0
[2020-07-24 21:45 INFO] # of circular seqs: 15997
[2020-07-24 21:45 INFO] # of linear seqs  : 880073
[2020-07-24 21:45 INFO] Finish spliting circular contig file with common rbs
[2020-07-24 21:45 INFO] Finish spliting linear contig file with common rbs
[2020-07-24 21:49 INFO] Step 1 - preprocess finished.
[2020-07-24 21:49 INFO] provirus mode is off; MAX_ORF_PER_SEQ set to 20; subsampling orf when orf number in a contig exceeds 20 to speed up the run
[2020-07-25 03:03 INFO] Step 2 - exract-feature finished.
Traceback (most recent call last):
  File "/scratch/eawebb/miniconda/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/add-suffix-seqname-keep-desc.py", line 5, in <module>
    import screed
ModuleNotFoundError: No module named 'screed'
/usr/bin/bash: full: command not found
[Sat Jul 25 03:04:37 2020]
Error in rule finalize:
    jobid: 8
    output: final-viral-combined.fa, final-viral-score.tsv
    shell:

            python /scratch/eawebb/miniconda/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/add-suffix-seqname-keep-desc.py iter-0/viral-fullseq.fa ||full > final-viral-combined.fa
            python /scratch/eawebb/miniconda/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/add-suffix-seqname-keep-desc.py iter-0/viral-lt2gene-w-hallmark.fa ||lt2gene >> final-viral-combined.fa
            cp iter-0/all-fullseq-proba.tsv final-viral-score.tsv
            N_viral_fullseq=$(grep -c '^>' iter-0/viral-fullseq.fa || :)
            N_viral_lt2gene=$(grep -c '^>' iter-0/viral-lt2gene-w-hallmark.fa || :)
            echo -e "
            ====> VirSorter run (non-provirus mode) finished.
            # of viral contigs:	$N_viral_fullseq
            # of short viral contigs (<2 genes):	$N_viral_lt2gene

            Useful output files:
            final-viral-score.tsv
            final-viral-combined.fa
            <====
            " | python /scratch/eawebb/miniconda/envs/virsorter2/lib/python3.8/site-packages/virsorter/./scripts/echo.py

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by jiarong** [comment]
fixed

**Comment by nduan1** [comment]
(base) -bash-4.2$ virsorter run -w /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out -i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.fa -j 4 --prep-for-dramv --use-conda-off
[2020-11-27 23:24 INFO] Using /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/template-config.yaml as config template
[2020-11-27 23:24 INFO] conig file written to /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out/config.yaml

[2020-11-27 23:24 INFO] Executing: snakemake --snakefile /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/Snakefile --directory /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out --jobs 4 --configfile /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out/config.yaml  --rerun-incomplete  --nolock --latency-wait 600   --quiet  all   
Job counts:
	count	jobs
	1	all
	1	check_point_for_reclassify
	1	circular_linear_split
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	combine_linear_circular
	5	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	5	gff_feature_by_group
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	5	merge_annotation_table_by_group_from_split
	1	merge_annotation_table_from_groups
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	6	merge_split_hmmtbl
	30	merge_split_hmmtbl_by_group
	30	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	5	split_faa_by_group
	5	split_gff_by_group
	138
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/circular-linear-split.py", line 6, in <module>
    import screed
ImportError: No module named screed
[Fri Nov 27 23:24:29 2020]
Error in rule circular_linear_split:
    jobid: 11
    output: iter-0/pp-seqname-length.tsv
    shell:
        
        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py --level error
            exit 1
        fi 

        python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/circular-linear-split.py           /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           0

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

module screed is missing, could you help me with this? Thanks!

**Comment by nduan1** [comment]
[2020-11-27 23:29 INFO] # of seqs < 0 bp and removed: 0
[2020-11-27 23:29 INFO] # of circular seqs: 1
[2020-11-27 23:29 INFO] # of linear seqs  : 8
[2020-11-27 23:30 INFO] Finish spliting linear contig file with common rbs
[2020-11-27 23:30 INFO] Finish spliting linear contig file with NCLDV rbs
[2020-11-27 23:30 INFO] Finish spliting circular contig file with common rbs
[2020-11-27 23:30 INFO] Finish spliting circular contig file with NCLDV rbs
[2020-11-27 23:30 INFO] Step 1 - preprocess finished.
  File "/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py", line 75
    f'Too many ({n_split}) splits requested on GFF file for '
                                                            ^
SyntaxError: invalid syntax
[Fri Nov 27 23:33:15 2020]
Error in rule split_gff_by_group:
    jobid: 94
    output: iter-0/ssDNA/all.pdg.gff.splitdir
    shell:
        
            rm -f iter-0/ssDNA/all.pdg.gff.splitdir/all.pdg.gff.*.split.prv.bdy
            rm -f iter-0/ssDNA/all.pdg.gff.splitdir/all.pdg.gff.*.split.prv.ftr
            rm -f iter-0/ssDNA/all.pdg.gff.splitdir/all.pdg.gff.*.anno
            rm -f iter-0/ssDNA/all.pdg.gff.splitdir/all.pdg.gff.*.affi.tab
            python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py iter-0/ssDNA/all.pdg.gff iter-0/ssDNA/all.pdg.gff.splitdir 100000
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

When I removed --use-conda-off, the error showed like this. @jiarong please help me with this, Thank you so much!

**Comment by jiarong** [comment]
My guess is 1) with `--use-conda-off`, the installed environment is not activated; 2) It's a bug. I have fixed it. Just update with instruction in development version.

**Comment by nduan1** [comment]
Thanks! That's great! I will try it again
