### ISSUE TITLE
Error in classify step

### ISSUE THREAD

**Issue by sejmodha** [jiarong/VirSorter2#38]
Hi There,

I get the following ValueError when running VirSorter2 pipeline.

```
cat /home/sej/VirSorter2/all_unknown.out/log/iter-0/step3-classify/provirus-score-ssDNA.log

Traceback (most recent call last):
  File "/home/sej/VirSorter2/virsorter/./scripts/classify-trimed.py", line 275, in <module>
    main()
  File "/home/sej/VirSorter2/db/conda_envs/75b80aa9/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sej/VirSorter2/db/conda_envs/75b80aa9/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sej/VirSorter2/db/conda_envs/75b80aa9/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sej/VirSorter2/db/conda_envs/75b80aa9/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sej/VirSorter2/virsorter/./scripts/classify-trimed.py", line 271, in main
    clf_trim_ins.load_data()
  File "/home/sej/VirSorter2/virsorter/./scripts/classify-trimed.py", line 82, in load_data
    indice = [ int(i) for i in indice ]
  File "/home/sej/VirSorter2/virsorter/./scripts/classify-trimed.py", line 82, in <listcomp>
    indice = [ int(i) for i in indice ]
ValueError: invalid literal for int() with base 10: '4.179426||'
```

**Comment by jiarong** [comment]
Hi, can you provide an example of your sequence name pattern? It would be great if you can find the one has "4.179426" in it.

**Comment by sejmodha** [comment]
Hi,

I have generated contigs using SPAdes assembler and yes there are numbers in the contig headers as SPAdes includes contig length and coverage in the contig header.

**Comment by jiarong** [comment]
Hi, I still can not identify the issue from your description alone. Could you share this file: /home/sej/VirSorter2/all_unknown.out/iter-0/all.pdg.hmm.tax
