### ISSUE TITLE
Error with virsorter2 

### ISSUE THREAD

**Issue by senukobla** [jiarong/VirSorter2#42]
I tried running virsorter2 but got the message below. Any ideas how I can resolve this 

[2021-02-13 22:33 INFO] conig file written to /fs/ess/PES0842/Data/senu/config.yaml

[2021-02-13 22:33 INFO] Executing: snakemake --snakefile /users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/Snakefile --directory /fs/ess/PES0842/Data/senu --jobs 48 --configfile /fs/ess/PES0842/Data/senu/config.yaml --conda-prefix /fs/ess/PES0842/Applications/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all   
Job counts:
	count	jobs
	1	all
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	5	hmmsearch
	5	hmmsearch_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	3	merge_split_hmmtbl
	20	merge_split_hmmtbl_by_group
	3	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	375	provirus_call_by_group_by_split
	451
[2021-02-14 02:59 ERROR] See error details in log/iter-0/step2-extract-feature/extract-feature-from-hmmout-common.log
[Sun Feb 14 02:59:02 2021]
Error in rule hmm_sort_to_best_hit_taxon:
    jobid: 26
    output: iter-0/all.pdg.hmm.tax, iter-0/all.pdg.hmm.ftr
    log: log/iter-0/step2-extract-feature/extract-feature-from-hmmout-common.log (check log file(s) for error message)
    conda-env: /fs/ess/PES0842/Applications/conda_envs/7a574821
    shell:
        
        python /users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/extract-feature-from-hmmout.py 30 "iter-0/all.pdg.Archaea.hmmtbl,iter-0/all.pdg.Bacteria.hmmtbl,iter-0/all.pdg.Eukaryota.hmmtbl,iter-0/all.pdg.Mixed.hmmtbl,iter-0/all.pdg.Viruses.hmmtbl" "arc,bac,euk,mixed,vir" > iter-0/all.pdg.hmm.tax 2> log/iter-0/step2-extract-feature/extract-feature-from-hmmout-common.log || { echo "See error details in log/iter-0/step2-extract-feature/extract-feature-from-hmmout-common.log" | python /users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        python /users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/add-unaligned-to-hmm-featrues.py iter-0/all.pdg.faa iter-0/all.pdg.hmm.tax > iter-0/all.pdg.hmm.ftr
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by jiarong** [comment]
Hi, thanks for the feedback. Can you paste the content of "log/iter-0/step2-extract-feature/extract-feature-from-hmmout-common.log" here?

**Comment by senukobla** [comment]
Traceback (most recent call last):
  File "/users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/extract-feature-from-hmmout.py", line 114, in <module>
    main()
  File "/users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/extract-feature-from-hmmout.py", line 101, in main
    d_tblout = get_dict_whole_seq(tblout_lis, tag_lis)  
  File "/users/PES0842/senukobla1/anaconda3/lib/python3.7/site-packages/virsorter/./scripts/extract-feature-from-hmmout.py", line 45, in get_dict_whole_seq
    e_val = float(lis[4])
ValueError: could not convert string to float: '----'

**Comment by jiarong** [comment]
Looks like there is an issue with hmmer output formatting. I need to see the input files to find the problem. Could you upload the following files:
iter-0/all.pdg.Archaea.hmmtbl
iter-0/all.pdg.Bacteria.hmmtbl
iter-0/all.pdg.Eukaryota.hmmtbl
iter-0/all.pdg.Mixed.hmmtbl
iter-0/all.pdg.Viruses.hmmtbl

**Comment by senukobla** [comment]
[all.pdg.Archaea.txt](https://github.com/jiarong/VirSorter2/files/6017754/all.pdg.Archaea.txt)
[all.pdg.Eukaryota.txt](https://github.com/jiarong/VirSorter2/files/6017755/all.pdg.Eukaryota.txt)
[all.pdg.Bacteria.txt](https://github.com/jiarong/VirSorter2/files/6017756/all.pdg.Bacteria.txt)
[all.pdg.Mixed.txt](https://github.com/jiarong/VirSorter2/files/6017757/all.pdg.Mixed.txt)
[all.pdg.Viruses.txt](https://github.com/jiarong/VirSorter2/files/6017758/all.pdg.Viruses.txt)

**Comment by senukobla** [comment]
[all.pdg.Archaea.txt](https://github.com/jiarong/VirSorter2/files/6017762/all.pdg.Archaea.txt)
[all.pdg.Eukaryota.txt](https://github.com/jiarong/VirSorter2/files/6017764/all.pdg.Eukaryota.txt)
[all.pdg.Bacteria.txt](https://github.com/jiarong/VirSorter2/files/6017765/all.pdg.Bacteria.txt)
[Uploading all.pdg.Mixed.txt…]()

**Comment by senukobla** [comment]
see files attached above . Sorry for the multiple posts. I think the first one has all the files

**Comment by senukobla** [comment]
Any updates on this problem . The files you requested are above

**Comment by jiarong** [comment]
Sorry for the delay. I found `all.pdg.Bacteria.txt` is corrupted, which might be caused by instability of hardware. Re-run the sample should resolve the problem.
