### ISSUE TITLE
Error related to circular-remove-partial-gene.py

### ISSUE THREAD

**Issue by hitig** [jiarong/VirSorter2#47]
Hi, I encountered this error when running virsorter 2.1 with contigs assembled using megahit. Actually, vs2 ran well using test file,  even when I subsample my input file to <=200 contigs, but error appeared when the input file has >=500 contigs. The error looks like this: 
##################################
[2021-03-08 18:28 INFO] VirSorter 2.1
[2021-03-08 18:28 INFO] $PATH/virsorter run -w vs2 -i ./contigs.lt1000.fas -j 36 all --use-conda-off
[2021-03-08 18:28 INFO] Using $PATH/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/template-config.yaml as config template
[2021-03-08 18:28 INFO] conig file written to $PATH/vs2/config.yaml

[2021-03-08 18:28 INFO] Executing: snakemake --snakefile $PATH/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/Snakefile --directory $PATH/vs2 --jobs 36 --configfile $PATH/vs2/config.yaml --latency-wait 600 --rerun-incomplete --nolock        --quiet  all   
Job counts:
	count	jobs
	1	all
	1	check_point_for_reclassify
	1	circular_linear_split
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	combine_linear_circular
	5	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	5	gff_feature_by_group
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	25	merge_split_hmmtbl_by_group
	25	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	5	split_faa_by_group
	5	split_gff_by_group
	121
[2021-03-08 18:28 INFO] # of seqs < 0 bp and removed: 0
[2021-03-08 18:28 INFO] # of circular seqs: 7704
[2021-03-08 18:28 INFO] # of linear seqs  : 837223
[2021-03-08 18:28 INFO] Finish spliting circular contig file with common rbs
[2021-03-08 18:28 INFO] Finish spliting circular contig file with NCLDV rbs
[2021-03-08 18:29 INFO] Finish spliting linear contig file with common rbs
[2021-03-08 18:29 INFO] Finish spliting linear contig file with NCLDV rbs
[2021-03-08 18:36 ERROR] See error detail in $PATH/vs2/log/iter-0/step1-pp/circular-remove-partial-gene-common.log
[Mon Mar  8 18:36:29 2021]
Error in rule remove_partial_gene:
    jobid: 130
    output: iter-0/pp-circular-flt.gff, iter-0/pp-circular-flt.faa
    shell:
        
        Log=$PATH/vs2/log/iter-0/step1-pp/circular-remove-partial-gene-common.log
        if [ circular = "circular" ]; then
            python $PATH/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/./scripts/circular-remove-partial-gene.py iter-0/pp-circular.gff iter-0/pp-circular-flt.gff &> $Log || { echo "See error detail in $Log" | python $PATH/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/./scripts/echo.py --level error; exit 1; }
            python $PATH/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/./scripts/filter-seqs-by-gff.py iter-0/pp-circular-flt.gff iter-0/pp-circular.faa iter-0/pp-circular-flt.faa
        else
            (cd iter-0 && ln -s pp-circular.gff pp-circular-flt.gff)
            (cd iter-0 && ln -s pp-circular.faa pp-circular-flt.faa)
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

#######################
circular-remove-partial-gene-common.log:

Traceback (most recent call last):
  File "/biostack/bioconda/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/./scripts/circular-remove-partial-gene.py", line 168, in <module>
    main()
  File "/biostack/bioconda/lib/python3.7/site-packages/virsorter-2.1-py3.7.egg/virsorter/./scripts/circular-remove-partial-gene.py", line 79, in main
    i.strip().split('=') for i in s.split(';')
ValueError: too many values to unpack (expected 2)

#############################
My contigs looks like:
>k141_5865184_flag=0_multi=3.9272_len=1048
ATATAAATTATGATATGGCTTAGAGAGGAGCTAAGGAAAATAGGAAGAATGGTAATAAGATGCCAGAAATACTACAAAGGAGTTGTTTTAAATGGAATGTTCAGGCAGACCTCATTGAGAAAGGGGCATTTTAAGAGCAGAATTGAAGGAGAGAGGGGAATTGAATCATGTGGAAATGGGTAAAGGAGTTGAGATGTGCGTGGCCAAGGACAGAGCCATTGGAAAATCAAGGAAGTGGGAGGAAATCTGCACAGGTGAGGATGAGGGAGGACAATATGACTGCAAAGGAGTGGGTGAGAAGGTGAGAGTAGTAAGTCAGGTCAGCATGGTAATCAGGGAGACCCTGGAAGCCTTTCACTCTCCTCTGTACTTTGTCTTTTACTCTTAAATAAGATACTGGAGTCTTGAGCAGAGAAATGGCATGACCAATGAAGCAGAATTGTTGCATCTATTATTTGTAGGGAATCAACTATAGAAACATGGAGGGGAATATAATATACCCCTTTAAGAGGTTATTTGACCTGGAGAATTAATAAAAACTTACATCACAGTGGTGTGTGTGCTAGCAGATACACACACACATACACACACACACAGACAGATATGAGAGACTGAAGTTTAAAAACACTGATGAAGAAAAGTAATCATGGATTTATAAATAGGACATTGAAGTTTCTTTCCAACCCAGAAGTTCCAGCATGCTGTGTAGACACTTGCAAGATGCTGTGGGATTCAATAACTCTGCCAATCCCACATCCTGGCCAGCATCAGGATTTCTCCTGAAATTCTATCATCAGCATTTAGATATCATTTTGTAAAAGAAGTCAGTTCCTATCTAAATTTGGTCACCCCTGGGATTTGCACTGTACAGGTAATTATCGCTAACATAATCATTTCAGTAAAGAAACAGAGAAAACTAAGGATCGATGTAGATAGGTTGTACTATATAAGCCCAAGAGAAACCATTCTTTGATGTGCAAGTTAATAGAAAACTGATCATTAGTATAAACCCTGTGTGATTGATGACCCAGCAGCCTTTGATGGAACT
>k141_4765462_flag=1_multi=5.0000_len=1232
AACATCGGGTACGCTGCCAACGAAATTGACATACCTACTTGGCTAATGGCTCCCAGCATCCAGGAGCTGCCCTGGCCTGGGGTGGGAGCCAGCTTCCGTCCAAGGAATGGCGCGATCACCAGATCAGTGGCTCTCGGCGTGCAGCCCACAGCCCAGCGGCCCCTGGGAGCCTGCAGAGACCACTCTCTTGGGTCCCACCTGAGACCTGCTGAGCTGGCAGCTCTGGGGGAACCAGCCCTGGGTCACCCTCAGCCACCTCCTGCCCACCCAGGGAAAGCCCTCACCAGACCTGTCCCCAGCCCCTCACTCCAGCCCCACATCCCTGGGAGCTCCTGGATCGCCCGCACTGAACCAGGTAAGAAGAAAACCGCACCTGTGGACAATGGGCACCCCTCCAGCCACACCGTCTGCCCCTCAAAAACCACTTCTCTTAATTCACAGTGAAATCTGCACCATAAAAATTGGAAGGAAAATAGAAAGAAAGAAAGAAAACTAACCTCCAAAGTCTTCCTCACCACTTTTCCCTCACTCTTGGCCAGGTGGCTGCTGCAGCCCTAGCTGCCTTCCTGGGCTGTCCCCTCCCTCACTAGTATGTCCCTTTCACCTCCACTGTCCAGTTAGCCTGGTCCCAGGCTTCCAGAGCAGCCTCGAGACGGCTTAAAGAACCCAGCGCCAGACCTGGGTCAGAAAGTGCAAACCCCTTCCCTCTGGGCTGGTCCCAGCAAAACGACACCCCAGAGCCCCAAACCTGACCCACAATGCCCTCACCTGAGCACCAAGGGGCTGGGTGGCCCTGACTGCCACTACCCCCCACGGCTCTCTGGTGTCACCAACCCGGCTTCTGCAGGAAACCACCCACCTGCTCTCTGTGACCTTGCTTCTCCTTATTAGGTCCCCTGGGCAGCTGGGTCCCTCCCCTGAGGGACACCTGAGCCTCCTCCTGGCCTCTGGTGCTCAGGACACAGTGGGCCCTCCTCTTCCCTCCAGCTTGACTTCCAGCGGCTCAGTGCTGCCCAGGAGGAAGCCCCCCTGCAGCTCCCTCAGCCTGAACGTCTTGGTTCCACCTTCACTTTTCCATGGTTCTGGGGATTCAAGCCAGTCCTGTTTCTCCTTGAGTTTTTGGTTTGGTTTGCAGCACTCTGGGTAGAACCCAGCCCTGGAGGCCAGGCAAGCCCTCTACCCCTGAGCCACACCCGCTGCCCTCTGCTTGAGCTTTTAAGTGAACTTTATTT
>k141_3849028_flag=1_multi=2.0716_len=1300
TAAGTTTAGTTGACTAAAATATATGGAGAGAGGTTTTACTTCTCTCCATTTTTAAGGAGAATAGTATGGAAGTAATCTTCTATTATAATCAGTCTGATGATAGAATGATAAATAAAGTTTTGTTGCAAGGAGAGACTTTGGAAGGAGTTATGCGTGGAGAATGTAATATTATGTCTCCAAGCATAAGATTTGAAAGCGCAAATGTACTTAGATATAATTACTGCTATATTCCAGAACTTCAGCGTTACTATACCGTTGTTACTAATAATATCGTTCGTAATGGCGTATATGATATAACTTTTGAAGTTGATGTTTTAATGTCATTTCGCGGCGATATAATGAAACTTCAATGTATTGTTGATAAGCAAACCGAGCTTGTTAACGGAGATGAATATATCGACGATGGATCGCTTGTTTGCGATAATATCATGTTTAATAGGATATATGAATTTTCGGCTGGTTTTAACAATTCGCCGGAATATATCTTAATAACCGCTGGTTAGTTTAGTTAACTGGAAAGGATGCAATATTATGGGAACAATTATTGAATGGGCTAATTGGACGCAAGCGAAAGAAGCAATAGCTCAGACGTCGAAAGCAGTATCGGGAATGTCTCCGGCAGAAGCAGAAGCGGCACTTAATTGGAGTAAAACTACTCTTAAAGACGGCACTATTCGATATATACACAATGCTTCAAGCGGAGCTGGAGGAAGCAATGTTGTTCAATTTCCGGGAGCAAGTGCATCTGATGCTTTTAATAGTTATGTTGGAGATGGCGGTTTGTCAAGTTCTGGCGGCGCGGCTGTTAGTAATCCTGCAAGCGCTCAAAGTTCTAATCTCACTATGCTAAAAGGAGCAACAGGTACAACTGGTATTGGTGCAATTCTTTCAATGAATCTGCCAACTGCGGCGGCGGCTATCGCTCCATTGGCAGGTGCAGCACTTGGAGTCGGGTTATATGAATTAAATCCTGATTTATGGAATAAGATAAGTAGAGCTTTGCTACCTTTCTGCTATGATGATAGTGAATTACTTCCAGTTGTTGCTAATGAAAGCGGAGATACTTTTTTTCCTCTTGACGCTGTTAGAGCAGTAGTTGATGCTCTTAATAATAATATAAAGGATGGAGTAGGTACTCCAAATGCTACTGAGTTTCCAAATTTTGAACAAATATATAATCCATATCCTGTTTCTGTTCTTCGCGGAGTAAAGCATATAGAATATAGCTATTCATTTACAGGCGCTCAAAATAAAGAGAAAAAGTATTATTACAGAGTTAATTCTACAATGCCATTTGATT

Can you help me with this error?? many thanks.

**Comment by jiarong** [comment]
Hi, this bug is probably cased by "=" in your sequence headers. You can just remove or place it with anything other than "=", ";", or ":".  I will fix this in next release.

**Comment by hitig** [comment]
It seems so, thank you for your immediate response.

**Comment by hitig** [comment]
Hi Jiarong, I have another question, how to extract circular genomes from results? I have noticed there is circular shape in final-viral-boundary.tsv, but not every sequence labeled circular is categorized in final-viral-combined.fa.

**Comment by jiarong** [comment]
Right, there are sequences in `final-viral-boundary.tsv` not end up in `final-viral-combined.fa` and should be ignored.
