### ISSUE TITLE
Issue with running Virsorter

### ISSUE THREAD

**Issue by haleyhallowell** [jiarong/VirSorter2#48]
Hello, 

I currently have Virsorter 2.1 installed onto a remote super computer, and am having issues with the template-config.yaml file. When I run this code: 

 `virsorter run --seqfile contig.fa --working-dir home/aubhah/pigproject/analysis/10_virsorter`

I get this back: 
[2021-03-09 11:03 INFO] Using /home/aubhah/.virsorter/template-config.yaml as config template
Traceback (most recent call last):
  File "/opt/asn/apps/virsorter_2.1/bin/virsorter", line 10, in <module>
    sys.exit(cli())
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/virsorter/virsorter.py", line 330, in run_workflow
    make_config(
  File "/opt/asn/apps/virsorter_2.1/lib/python3.8/site-packages/virsorter/config.py", line 147, in make_config
    groups_avail = os.listdir(f'{db_dir}/group')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/beegfs/apps/dmc/apps/virsorter_2.1/group'

The admins for the supercomputer installed this, not myself so I'm not sure what to do here. If it's something they need to fix on their end, I can gladly pass along the information. 

Thanks!

**Comment by jiarong** [comment]
Looks like the database is not set up right. You can ask your server admin where the database is installed and add "-d /PATH/To/DATABASE" in your command.
