### ISSUE TITLE
Conda and VirSorter env requirements

### ISSUE THREAD

**Issue by dbenaben** [jiarong/VirSorter2#54]
Hello,

We installed VirSorter 2.0 and 2.1 on a HPC infrastructure using conda package (on a shared directory without user write permission).

And VirSorter failed with `No module named 'screed'`
```
$ virsorter setup -d db -j 4 --skip-deps-install
$ virsorter run --use-conda-off -w Test.out -i test.fa -j 4 all
[2021-03-22 08:37 INFO] VirSorter 2.1
[...]
Traceback (most recent call last):
  File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/virsorter/./scripts/circular-linear-split.py", line 6, in <module>
    import screed
ModuleNotFoundError: No module named 'screed'
```
Indeed, `screed` is not installed by the conda package: https://anaconda.org/bioconda/virsorter

But it seems required: https://github.com/jiarong/VirSorter2/blob/master/virsorter/envs/vs2.yaml

I'm a little bit lost. Conda package does not seem to reflect the virsorter env.

Software directory is not writable for users, so VirSorter fail to install missing packages if we not use `--skip-deps-install` and `--use-conda-off ` options.
But conda should have installed all requirements, no ?

So I wonder the best way to manage this (create an issue on bioconda recipe or just install all dependencies required ?).

Thanks for your help,

**Comment by jiarong** [comment]
Hi, VirSorter2 installs most of its dependencies (for its internal pipeline) with `virsorter setup`, and it install them into the `db` directory owned by you, isolated from the VirSorter2 env itself. You do not need to be server sys admin to run that. So you do not need to add `--skip-deps-install`. 
If your server sys admin do not like users install their own envs, you can him/her to run `virsorter setup` to put the `db` in a shared location too.

The `--skip-deps-install` and `--use-conda-off` is designed for the development version, where all deps are installed under VirSorter2 env.

**Comment by dbenaben** [comment]
Hi, I'm sorry for the late reply (I wanted to test again).
In our site, virsorter is installed by admin with conda. And when users try to setup their environment, conda try to install virsorter dependencies in this installation directory (wihtout users write permission) and rise a 'Permission denied' error:
```
$ virsorter setup -d db -j 4
[2021-03-30 09:42 INFO] VirSorter 2.1
[2021-03-30 09:42 INFO] /shared/ifbstor1/software/miniconda/envs/virsorter-2.1/bin/virsorter setup -d db -j 4
[2021-03-30 09:42 INFO] Setting up VirSorter2 database; this might take ~10 mins and only needs to be done once.
[2021-03-30 09:42 INFO] Attention: can not write template-config.yaml in source directory:
/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/virsorter
makeing a copy to user home direcotry:
/shared/home/dbenaben/.virsorter/template-config.yaml

[2021-03-30 09:42 INFO] Using {template} as config template
[2021-03-30 09:42 INFO] saving /shared/ifbstor1/home/dbenaben/db as DBDIR to config file /shared/home/dbenaben/.virsorter/template-config.yaml
CreateCondaEnvironmentException:
Could not create conda environment from /shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/mamba/mamba_env.py", line 42, in mamba_install
        index = load_channels(
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/mamba/utils.py", line 93, in load_channels
        index = get_index(
      File "/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/lib/python3.9/site-packages/mamba/utils.py", line 62, in get_index
        api.create_cache_dir(), api.cache_fn_url(full_url)
    RuntimeError: Permission denied: '/shared/ifbstor1/software/miniconda/envs/virsorter-2.1/pkgs/cache'
```
We will try to add VirSorter requirments in our environment.

**Comment by jiarong** [comment]
The issue is the directory for temporary downloaded files  is not writable. Maybe this can help: https://docs.anaconda.com/anaconda/user-guide/tasks/shared-pkg-cache/

Anyways, I think in this case asking the admin to `virsorter setup` a shared `db` is the most straightforward way. It's strange that they install the tool without the db..
Or you can install your own version following the installation instructions, so you do everything in your own user space.

**Comment by dbenaben** [comment]
Thank you for your feedback.
We install automatically our packages (with conda) and don't do tasks like `virsorter setup` after conda install.
I'm going to try to "containerize" virsorter.

**Comment by nick-youngblut** [comment]
@jiarong editing any files within the codebase via the cli tool will lead to such `permission denied` errors. This is why config/database/etc files are kept separate from the codebase. 

It appears that the config yaml path is hard-coded. Would it be possible for you enable `--config-path` so that the user can set the config path via the cli (or at least via an env variable such as `VIRSORTER_CONFIG=/path/to/config`)?

**Comment by jiarong** [comment]
Thanks for the suggestion on config file through env variable or cli, which is more common and less confusing..
VirSorter2 currently has an alternative mechanism dealing with "no write permission" issue. It will create a directory `.virsorter` at `$HOME`, and put the config file there. This has been tested and works well with conda install. The problem here is with container install. It is trying to create a directory `.virsorter` under `/home/gitpod` within the container while you are outside the container. You need to docker shell into the container first.
Also `--db-dir/-d` option is available at cli for the main subcommand `virsorter run`.
