### ISSUE TITLE
issue with ValueError when running VirSorter 2.2.2 for test.fa

### ISSUE THREAD

**Issue by WEIdlam** [jiarong/VirSorter2#77]
Dear jiarong,
I'm using virsoter 2.2.2 and stucked in an error when running virsorter for test.fa. The error occur after Step 2 - extract-feature finished. I have tried to reinstall it according to the requirements, but the same mistakes still occur.
The linux command is:
virsorter run -w test.out -i test.fa --min-length 1500 -j 4 all
Here is the error message:
Step 1 - preprocess finished.
[2021-07-07 06:50 INFO] Step 2 - extract-feature finished.
[2021-07-07 06:50 ERROR] See error details in /public/home/hyy/virus/VirSorter2/VirSorter2/test.out/log/iter-0/step3-classify/all-score-ssDNA.log
[Wed Jul  7 06:50:30 2021]
Error in rule classify_by_group:
    jobid: 57
    output: iter-0/ssDNA/all.pdg.clf
    conda-env: /public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00
    shell:
        
        Log=/public/home/hyy/virus/VirSorter2/VirSorter2/test.out/log/iter-0/step3-classify/all-score-ssDNA.log
        python /public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py iter-0/ssDNA/all.pdg.ftr /public/home/hyy/virus/VirSorter2/VirSorter2/db/group/ssDNA/model ssDNA iter-0/ssDNA/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[2021-07-07 06:50 ERROR] See error details in /public/home/hyy/virus/VirSorter2/VirSorter2/test.out/log/iter-0/step3-classify/all-score-dsDNAphage.log
[Wed Jul  7 06:50:30 2021]
Error in rule classify_by_group:
    jobid: 56
    output: iter-0/dsDNAphage/all.pdg.clf
    conda-env: /public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00
    shell:
        
        Log=/public/home/hyy/virus/VirSorter2/VirSorter2/test.out/log/iter-0/step3-classify/all-score-dsDNAphage.log
        python /public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py iter-0/dsDNAphage/all.pdg.ftr /public/home/hyy/virus/VirSorter2/VirSorter2/db/group/dsDNAphage/model dsDNAphage iter-0/dsDNAphage/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

 **This error details  **
all-score-dsDNAphage.log:

Traceback (most recent call last):
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py", line 56, in main
    X = X.loc[:, SELECT_FEATURE_LIST]
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 1109, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 806, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 1143, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got CommentedSeq)

all-score-ssDNA.log:

Traceback (most recent call last):
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/virsorter/./scripts/classify.py", line 56, in main
    X = X.loc[:, SELECT_FEATURE_LIST]
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 1109, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 806, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/indexing.py", line 1143, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "/public/home/hyy/virus/VirSorter2/VirSorter2/db/conda_envs/dfa44b00/lib/python3.8/site-packages/pandas/core/common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got CommentedSeq)
 
Thanks!

**Comment by jiarong** [comment]
Hi, thanks for timely bug report. The new pandas release last weekend is breaking the code. I fixed it in development version. I will update bioconda in a day or two.

**Comment by MengZhang2019** [comment]
> Hi, thanks for timely bug report. The new pandas release last weekend is breaking the code. I fixed it in development version. I will update bioconda in a day or two.

Hi, I meet the same issue. When can you solve this, or which version pandas should be used in the current version of VirSort2. Looking forward to your reply, Thanks.

**Comment by WEIdlam** [comment]
Hi, the author has fixed it&nbsp;in development version. u can follow the tutorial to&nbsp;reinstall it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月15日(星期四) 中午11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jiarong/VirSorter2] issue with ValueError when running VirSorter 2.2.2 for test.fa (#77)





  
Hi, thanks for timely bug report. The new pandas release last weekend is breaking the code. I fixed it in development version. I will update bioconda in a day or two.
  
Hi, I meet the same issue. When can you solve this, or which version pandas should be used in the current version of VirSort2. Looking forward to your reply, Thanks.

**Comment by MengZhang2019** [comment]
It's worked now, thanks!

**Comment by jiarong** [comment]
It's also fixed in the latest bioconda verison (v2.2.3).
