### ISSUE TITLE
error when  increase the threads for hmmsearch

### ISSUE THREAD

**Issue by mujiezhang** [jiarong/VirSorter2#79]
Hi,
I am using VirSorter2 to predict viruses from bacteria genomes. I want to speed up it and run the command "virsorter config --set HMMSEARCH_THREADS=4". Then I got the following error:

(vs2) [clsjhh@login2 ~]$ virsorter config --set HMMSEARCH_THREADS=4
[2021-07-07 22:11 INFO] VirSorter 2.2.2
[2021-07-07 22:11 INFO] /lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/bin/virsorter config --set HMMSEARCH_THREADS=4
Traceback (most recent call last):
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/bin/virsorter", line 10, in <module>
    sys.exit(cli())
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/site-packages/virsorter/virsorter.py", line 925, in config
    val = os.path.abspath(val)
  File "/lustre/home/acct-clsjhh/clsjhh/anaconda3/envs/vs2/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not int

I do not know the reason...

**Comment by jiarong** [comment]
Hi, I can not reproduced the error.. You might have config file from previous versions. You can use the following command to locate it and change "HMMSEARCH_THREADS" directly in it.

**Comment by mujiezhang** [comment]
Thanks you! I reinstalled virsorter2, and resolved it. But I wonder why the  HMMSEARCH_THREADS=2. Since the virsorter2 spend most of the run time in annotation, why do not set more threads for hmmsearch?

**Comment by jiarong** [comment]
The season for setting threads at 2 is that hmmsearch is not efficient at in using the cpus when the threads number is larger than 2. My experience is 4 is the maximum it can use in our server.
