### ISSUE TITLE
Invalid syntax error after VirSorter2 download

### ISSUE THREAD

**Issue by LeoBusse** [jiarong/VirSorter2#8]
Hello! I installed VirSorter2 with miniconda2. However, when I try to run the virsorter -h command, I get an error reading Syntax Error: invalid syntax. The program successfully installed, so I'm not sure what is causing the error. This is the full error message I receive:

virsorter -h
Traceback (most recent call last):
  File "/Users/leorabusse/miniconda2/bin/virsorter", line 11, in <module>
    load_entry_point('virsorter', 'console_scripts', 'virsorter')()
  File "/Users/leorabusse/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/leorabusse/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/leorabusse/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/leorabusse/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/leorabusse/VirSorter2/virsorter/virsorter.py", line 675
    mes = f'config file path: {TEMPLATE}\n'
                                          ^
SyntaxError: invalid syntax

I'm pretty new to programming, and any and all help is appreciated! 
Thanks so much

**Comment by jiarong** [comment]
Hi, thanks for the feedback. The issue is the default python in your current environment is python2, but VirSorter2 needs python3. You can just follow the "development version" of installation instruction (option 2). That should solve your problem.

**Comment by LeoBusse** [comment]
Thanks! I was able to install it successfully this time. However, when trying to install the dependencies for the programs, I continue to get a couple errors:

(vs2) Leoras-MacBook-Air:VirSorter2 leorabusse$ virsorter setup -d db -j 4
[2020-10-01 19:18 INFO] Setting up VirSorter2 database; this might take ~10 mins and only needs to be done once.
[2020-10-01 19:18 INFO] saving to /Users/leorabusse/VirSorter2/db as DBDIR to config file /Users/leorabusse/VirSorter2/virsorter/template-config.yaml
CreateCondaEnvironmentException:
Could not create conda environment from /Users/leorabusse/VirSorter2/virsorter/rules/../envs/vs2.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - libgfortran-ng=7.3.0
  - _openmp_mutex=4.5
  - libstdcxx-ng=9.2.0
  - libgcc-ng=9.2.0


  File "/Users/leorabusse/.conda/envs/vs2/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 332, in create
[2020-10-01 19:22 ERROR] CreateCondaEnvironmentException:
Could not create conda environment from /Users/leorabusse/VirSorter2/virsorter/rules/../envs/vs2.yaml:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - libgfortran-ng=7.3.0
  - _openmp_mutex=4.5
  - libstdcxx-ng=9.2.0
  - libgcc-ng=9.2.0


  File "/Users/leorabusse/.conda/envs/vs2/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 332, in create

Do you have any advice on how to navigate this issue? Do I need to create a different environment?

Thank you!

**Comment by jiarong** [comment]
I see you are installing on your mac. VirSorter2 does not support Mac OS at the moment. You need linux OS to install it. VirSorter2 runs are typically very computationally intensive due to large viral protein HMM database, so it is recommended to run on Linux servers.
You can use virtualbox (https://www.virtualbox.org/) or Vagrant (https://www.vagrantup.com/) to setup linux (virtual machine) on your mac, just for testing the tool.
