### ISSUE TITLE
CreateCondaEnvironmentException: Could not create conda environment from /VirSorter2/virsorter/rules/../envs/vs2.yaml

### ISSUE THREAD

**Issue by lifeifeifeifei** [jiarong/VirSorter2#88]
I install the virsorter2 as suggested:

```
conda create -n vs2 -c conda-forge -c bioconda "python>=3.6" scikit-learn=0.22.1 imbalanced-learn pandas seaborn hmmer==3.3 prodigal screed ruamel.yaml "snakemake>=5.18,<=5.26" click mamba
conda activate vs2
git clone https://github.com/jiarong/VirSorter2.git
cd VirSorter2
pip install -e .

tar -xzf db.tgz
virsorter config --init-source --db-dir=./db

```

but when I run it on a test dataset, it always report error. 

```
virsorter run -w test.out -i test.fa --min-length 1500 -j 4 all
[2021-10-11 08:04 INFO] VirSorter 2.2.3
[2021-10-11 08:04 INFO] /Software/anaconda3/envs/vs2/bin/virsorter run -w test.out -i test.fa --min-length 1500 -j 4 all
[2021-10-11 08:04 INFO] Using /Software/VirSorter2/virsorter/template-config.yaml as config template
[2021-10-11 08:04 INFO] conig file written to /test.out/config.yaml

[2021-10-11 08:04 INFO] Executing: snakemake --snakefile /Software/VirSorter2/virsorter/Snakefile --directory /test.out --jobs 4 --configfile /test.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock --conda-frontend mamba --conda-prefix /Software/VirSorter2/db/conda_envs --use-conda --quiet all
CreateCondaEnvironmentException:
Could not create conda environment from /Software/VirSorter2/virsorter/rules/../envs/vs2.yaml:
`>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<`
Traceback (most recent call last):
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 141, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/mamba/mamba_env.py", line 42, in mamba_install
    index = load_channels(pool, channel_urls, repos, prepend=False)
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/mamba/utils.py", line 123, in load_channels
    index = get_index(
  File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/mamba/utils.py", line 104, in get_index
    is_downloaded = dlist.download(True)
RuntimeError: Multi-download failed.
$ /Software/anaconda3/envs/vs2/bin/mamba create --quiet --file /Software/VirSorter2/db/conda_envs/7cf0ba25.yaml --prefix /Software/VirSorter2/db/conda_envs/7cf0ba25

An unexpected error has occurred. Conda has prepared the above report.

File "/Software/anaconda3/envs/vs2/lib/python3.8/site-packages/snakemake/deployment/conda.py", line 350, in create

```

**Comment by jiarong** [comment]
Sorry for the late reply. It looks like failing to install the required packages. Does the server have internet connection?

**Comment by gubingyu** [comment]
I have the same question now,I really hope it can be resolved. Thank you

**Comment by gubingyu** [comment]
I use this command virsorter setup -d db -j 4, it report error .
I have tried many methods, but still can not solve, hope to get help, thank you
The error :
[2021-11-17 18:04 INFO] VirSorter 2.2.3
[2021-11-17 18:04 INFO] /home/zhanyuanchao/miniconda3/envs/vs2/bin/virsorter setup -d db -j 4
[2021-11-17 18:04 INFO] Setting up VirSorter2 database; this might take ~10 mins and only needs to be done once.
[2021-11-17 18:04 INFO] saving /home/zhanyuanchao/software/Virsorter2/db as DBDIR to config file 
/home/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/template-config.yaml

CreateCondaEnvironmentException:
Could not create conda environment from /home/miniconda3/envs/vs2/lib/python3.8/site-packages/virsorter/rules/../envs/vs2.yaml:
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
ERROR   Path already locked by the same PID
WARNING LockFile creation for path '/home/miniconda3/envs/vs2/pkgs/cache' failed, continuing without it
Exceeded max retries, giving up
LockError: 
LOCKERROR: It looks like conda is already doing something.
The lock ['/home/miniconda3/envs/vs2/pkgs/cache.pid3095.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock

**Comment by lianzhh** [comment]
It might be you can't install packages through mamba！You can try to change “--conda-frontend mamba" to “--conda-frontend conda". Though it is slow, but it did works.

**Comment by jiarong** [comment]
The conda installation might have issue with certain OS with specific setting. I recommend the [singularity version](https://github.com/jiarong/VirSorter2#option-3).
