### ISSUE TITLE
ValueError: not enough values to unpack (expected 7, got 0)

### ISSUE THREAD

**Issue by VrusaWvary** [jiarong/VirSorter2#9]
Hello,
when I run ` virsorter run -w final-viral-boundary.tsv -i input.fa --include-groups "dsDNAphage,ssDNA" -j 8 --min-sco
re 0.8 --db-dir references/virsorter2_db --use-conda-off ` command, I get an error reading ValueError: not enough values to unpack (expected 7, got 0), I ran many samples, most of them were running normally, only this one reported an error, And input.fa is no abnormal, This is the full error message I receive:
```
Traceback (most recent call last):
  File "/share/data1/apps/miniconda3/envs/src/virsorter2-master/virsorter/./scripts/provirus.py", line 594, in <module>
    main()
  File "/share/data1/apps/miniconda3/envs/eeb8d9c0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/share/data1/apps/miniconda3/envs/eeb8d9c0/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/share/data1/apps/miniconda3/envs/eeb8d9c0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/share/data1/apps/miniconda3/envs/eeb8d9c0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/share/data1/apps/miniconda3/envs/src/virsorter2-master/virsorter/./scripts/provirus.py", line 591, in main
    provirus_ins.find_boundary()
  File "/share/data1/apps/miniconda3/envs/src/virsorter2-master/virsorter/./scripts/provirus.py", line 531, in find_boundary
    self.process_one_contig(last_seqname, mat)
  File "/share/data1/apps/miniconda3/envs/src/virsorter2-master/virsorter/./scripts/provirus.py", line 369, in process_one_contig
    self.trim_ends(df_gff, df_tax, 
  File "/share/data1/apps/miniconda3/envs/src/virsorter2-master/virsorter/./scripts/provirus.py", line 243, in trim_ends
    final_start, _, final_ind_start, _, _, _, _ = lis
ValueError: not enough values to unpack (expected 7, got 0)
```
I'm pretty new to programming, and any and all help is appreciated!
Thanks so much

**Comment by jiarong** [comment]
Hi, sorry for the late reply. it's been hectic for me recently. I have tried to fix the code to be more error proof. You can update by redo the instruction on installing development version, or `conda activate` the env for the current installation, `cd` into the cloned directory, then type `git pull` and `pip install -e .` Let me know if it solves your issue.

**Comment by VrusaWvary** [comment]
Thanks for the help, it solves my issue. I tried running this same analysis with new version, and this time I not received the same error message.
