### ISSUE TITLE
Error in rule split_contig_file

### ISSUE THREAD

**Issue by bramvandijk88** [jiarong/VirSorter2#95]
Dear devs,

I've got the following error when trying to run the test data:

```
Traceback (most recent call last):
  File "/home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py", line 13, in <module>
    type=click.Choice(['info', 'warning', 'error'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
Traceback (most recent call last):
  File "/home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py", line 13, in <module>
    type=click.Choice(['info', 'warning', 'error'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
[Thu Dec  9 17:09:48 2021]
Error in rule split_contig_file:
[Thu Dec  9 17:09:48 2021]
    jobid: 68
Error in rule split_contig_file:
    output: iter-0/pp-circular.fna.splitdir
    jobid: 69
    conda-env: /groups/micropop/Data/Quistad/CrassXenoseq_ReadMap_lt10000/virsorter/db/conda_envs/5eeb033e
    output: iter-0/pp-linear.fna.splitdir
    shell:

        Log=/groups/micropop/Data/Quistad/CrassXenoseq_ReadMap_lt10000/virsorter/test.out/log/iter-0/step1-pp/split-contig-file-circular-common.log
        Total=$(grep -v '^>' iter-0/pp-circular.fna | wc -c)
        Bname=$(basename iter-0/pp-circular.fna)
        # clean up output from following steps to avoid bug with checkpoint
        rm -f iter-0/pp-circular.fna.splitdir/pp-circular.fna.*.split.pdg.splitgff
        rm -f iter-0/pp-circular.fna.splitdir/pp-circular.fna.*.split.pdg.splitfaa
        if [ $Total -gt 30000000 ]; then
            python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/split-seqfile-even-bp-per-file.py iter-0/pp-circular.fna iter-0/pp-circular.fna.splitdir 30000000 &> $Log || { echo "See error details in $Log" | python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        else
            mkdir -p iter-0/pp-circular.fna.splitdir
            (cd iter-0/pp-circular.fna.splitdir && ln -sf ../$Bname $Bname.0.split)
        fi
        echo "Finish spliting circular contig file with common rbs" | python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    conda-env: /groups/micropop/Data/Quistad/CrassXenoseq_ReadMap_lt10000/virsorter/db/conda_envs/5eeb033e

    shell:

        Log=/groups/micropop/Data/Quistad/CrassXenoseq_ReadMap_lt10000/virsorter/test.out/log/iter-0/step1-pp/split-contig-file-linear-common.log
        Total=$(grep -v '^>' iter-0/pp-linear.fna | wc -c)
        Bname=$(basename iter-0/pp-linear.fna)
        # clean up output from following steps to avoid bug with checkpoint
        rm -f iter-0/pp-linear.fna.splitdir/pp-linear.fna.*.split.pdg.splitgff
        rm -f iter-0/pp-linear.fna.splitdir/pp-linear.fna.*.split.pdg.splitfaa
        if [ $Total -gt 30000000 ]; then
            python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/split-seqfile-even-bp-per-file.py iter-0/pp-linear.fna iter-0/pp-linear.fna.splitdir 30000000 &> $Log || { echo "See error details in $Log" | python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        else
            mkdir -p iter-0/pp-linear.fna.splitdir
            (cd iter-0/pp-linear.fna.splitdir && ln -sf ../$Bname $Bname.0.split)
        fi
        echo "Finish spliting linear contig file with common rbs" | python /home/vandijk/.conda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues
```

I have installed a conda environment according to the installation instructions. As the error clearly is python related, here's my python version:

```
> python -V
Python 3.8.12
```

Any ideas what's happening here?

**Comment by jiarong** [comment]
Hi, it looks like you have older `click` module installed. Try this to update in the vs2 conda environment:
`conda install click>=7`

**Comment by bramvandijk88** [comment]
> Hi, it looks like you have older `click` module installed. Try this to update in the vs2 conda environment: `conda install click>=7`

I've updated click, but the error is still the same. Here's my version of click:

```
conda list | grep "click"
click                     8.0.3            py38h578d9bd_1    conda-forge
```

**Comment by bramvandijk88** [comment]
> Can you try:
> 
> ```
> conda activate /groups/micropop/Data/Quistad/CrassXenoseq_ReadMap_lt10000/virsorter/db/conda_envs/5eeb033e
> conda list | grep "click"
> ```

click                     8.0.3            py38h578d9bd_1    conda-forge

**Comment by jiarong** [comment]
With version  >=7, the error should not happen... You might have changed some PATH or PYTHONPATH setting in your systems, so that python is not properly using the modules installed in vs2..

**Comment by jiarong** [comment]
Hi, check out the [singularity option](https://github.com/jiarong/VirSorter2#option-3) if this is still an issue.
