### ISSUE TITLE
KeyError 'max_score' during rule finalize

### ISSUE THREAD

**Issue by TLStach** [jiarong/VirSorter2#97]
Hello,

Thank you for writing VirSorter2! 
When running v2.2.3 on a small dataset I got a KeyError 'max_score'.

Traceback (most recent call last):
  File "[...]/db/conda_envs/112f6d1c/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'max_score'

I guess that this results from a lack of identified viral sequences in the data set. Thus, the 'viral-combined-proba.tsv' table is empty and the 'max_score' column is not created in the next step. I saw that you had the following code in 'add-extra-to-table.py'.

line 45 ..
    # seqname is index
    df_info['seqname'] = df_info.index

    df = pd.read_csv(score_f, sep='\t', header=0)
    if len(df) == 0:
        cols = df.columns.values.tolist() + ['max_score_group',
                'length', 'hallmark', 'viral', 'cellular']
        with open(outfile, 'w') as fw:
            fw.write('{}\n'.format('\t'.join(cols)))
            sys.exit(0)
            
I added 'max_score' to the list of cols names in the brackets to create this column if len(df) == 0.

This solved the problem for me. I hope that it makes sense to do so or could there be another reason or solution for it?

Thank you!

**Comment by jiarong** [comment]
Thanks for the bug report and solution!
